#Import modules

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

#Data preparation

In [3]:
sample_annot = pd.read_csv('drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/pancancer_metabolomics_v.0.3.4/pancancer_metabolomics/data/MasterMapping_MetImmune_03_16_2022_release.csv')
sample_annot

,CommonID,MetabID,ITHID,RNAID,MetabFile,MetabFile_sheet,ITHFile,RNAFile,RNA_raw_File,Dataset,Histology,TN,Identifier
0,OV:P1,P1,GSM642933_OC01_ARN0001_s1h1s1_U133p2.CEL.gz,GSM642933_OC01_ARN0001_s1h1s1_U133p2.CEL.gz,PreprocessedData_OV.xlsx,metabo_imputed_filtered_Tumor,MergedDeconvolution.GSE26193.csv,GSE26193.hgu133plus2.gene_symbol.csv,GSE26193.hgu133plus2.gene_symbol.csv,OV,HGSOC,Tumor,OV
1,OV:P2,P2,GSM642966_OC01_ARN0049_s2h1s1_U133p2.CEL.gz,GSM642966_OC01_ARN0049_s2h1s1_U133p2.CEL.gz,PreprocessedData_OV.xlsx,metabo_imputed_filtered_Tumor,MergedDeconvolution.GSE26193.csv,GSE26193.hgu133plus2.gene_symbol.csv,GSE26193.hgu133plus2.gene_symbol.csv,OV,HGSOC,Tumor,OV
2,OV:P41,P41,GSM642979_OC01_ARN0072_s1h1s1_U133p2.CEL.gz,GSM642979_OC01_ARN0072_s1h1s1_U133p2.CEL.gz,PreprocessedData_OV.xlsx,metabo_imputed_filtered_Tumor,MergedDeconvolution.GSE26193.csv,GSE26193.hgu133plus2.gene_symbol.csv,GSE26193.hgu133plus2.gene_symbol.csv,OV,HGSOC,Tumor,OV
3,OV:P42,P42,GSM643007_OC01_ARN0118_s1h1s1_U133p2.CEL.gz,GSM643007_OC01_ARN0118_s1h1s1_U133p2.CEL.gz,PreprocessedData_OV.xlsx,metabo_imputed_filtered_Tumor,MergedDeconvolution.GSE26193.csv,GSE26193.hgu133plus2.gene_symbol.csv,GSE26193.hgu133plus2.gene_symbol.csv,OV,HGSOC,Tumor,OV
4,OV:P43,P43,GSM642949_OC01_ARN0026_s2h1s1_U133p2.CEL.gz,GSM642949_OC01_ARN0026_s2h1s1_U133p2.CEL.gz,PreprocessedData_OV.xlsx,metabo_imputed_filtered_Tumor,MergedDeconvolution.GSE26193.csv,GSE26193.hgu133plus2.gene_symbol.csv,GSE26193.hgu133plus2.gene_symbol.csv,OV,HGSOC,Tumor,OV
...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,LiCa2:LCS_683,LCS_683,GSM1979661_D6_683A.CEL.gz,GSM1979661_D6_683A.CEL.gz,PreprocessedData_ICC.xlsx,metabo_imputed_filtered_Tumor,MergedDeconvolution.GSE76297.csv,GSE76297.hugene20st.gene_symbol.csv,GSE76297.hugene20st.gene_symbol.csv,ICC,CCA,Tumor,LiCa2
984,LiCa2:LCS_684,LCS_684,GSM1979663_B5_684A.CEL.gz,GSM1979663_B5_684A.CEL.gz,PreprocessedData_ICC.xlsx,metabo_imputed_filtered_Tumor,MergedDeconvolution.GSE76297.csv,GSE76297.hugene20st.gene_symbol.csv,GSE76297.hugene20st.gene_symbol.csv,ICC,CCA,Tumor,LiCa2
985,LiCa2:LCS_685,LCS_685,GSM1979665_H4_685A.CEL.gz,GSM1979665_H4_685A.CEL.gz,PreprocessedData_ICC.xlsx,metabo_imputed_filtered_Tumor,MergedDeconvolution.GSE76297.csv,GSE76297.hugene20st.gene_symbol.csv,GSE76297.hugene20st.gene_symbol.csv,ICC,CCA,Tumor,LiCa2
986,LiCa2:LCS_687,LCS_687,GSM1979667_D6_687A.CEL.gz,GSM1979667_D6_687A.CEL.gz,PreprocessedData_ICC.xlsx,metabo_imputed_filtered_Tumor,MergedDeconvolution.GSE76297.csv,GSE76297.hugene20st.gene_symbol.csv,GSE76297.hugene20st.gene_symbol.csv,ICC,CCA,Tumor,LiCa2
987,LiCa2:LCS_688,LCS_688,GSM1979669_F1_688A.CEL.gz,GSM1979669_F1_688A.CEL.gz,PreprocessedData_ICC.xlsx,metabo_imputed_filtered_Tumor,MergedDeconvolution.GSE76297.csv,GSE76297.hugene20st.gene_symbol.csv,GSE76297.hugene20st.gene_symbol.csv,ICC,CCA,Tumor,LiCa2

In [4]:
sample_annot.RNAFile.value_counts()

RNAFile
GSE76297.hugene20st.gene_symbol.csv                              140
Cornell_PROSTATE.BatchAdj.hugene20st.gene_symbol.csv             137
MultiRegionalRCC.tpm.gene_symbol.csv                             114
GSE37751.hugene10st.gene_symbol.csv                              108
CPTAC_GBM_htseq_rna_04_09_2021.tpm.gene_symbol.csv                80
GSE89076.Agilent8x60K.log2_transformed.gene_symbol.csv            76
Multiregions.2Batchs.Sample.hg19KnownGene.tpm.gene_symbol.csv     76
Cornell_DLBCL.tpm.gene_symbol.csv                                 62
GSE26193.hgu133plus2.gene_symbol.csv                              45
GSE62452.hugene10st.gene_symbol.csv                               39
Project_08402_M.tpm.gene_symbol.csv                               32
HCC.tpm.gene_symbol.csv                                           31
Flow4Batch.tpm.gene_symbol.csv                                    30
PMC4187326_BRCA.tpm.gene_symbol.csv                               18
Name: count, dtype: int64

In [5]:
microarrays = ["GSE76297.hugene20st.gene_symbol.csv",
               "Cornell_PROSTATE.BatchAdj.hugene20st.gene_symbol.csv",
               "GSE37751.hugene10st.gene_symbol.csv",
               "GSE89076.Agilent8x60K.log2_transformed.gene_symbol.csv",
               "Multiregions.2Batchs.Sample.hg19KnownGene.tpm.gene_symbol.csv",
               "GSE26193.hgu133plus2.gene_symbol.csv",
               "GSE62452.hugene10st.gene_symbol.csv"

]

In [6]:
sample_annot_microarrays = sample_annot[sample_annot['RNAFile'].isin(microarrays)]
sample_annot_microarrays = sample_annot_microarrays.drop_duplicates(subset=['RNAFile'], keep = 'first')
sample_annot_microarrays

,CommonID,MetabID,ITHID,RNAID,MetabFile,MetabFile_sheet,ITHFile,RNAFile,RNA_raw_File,Dataset,Histology,TN,Identifier
0,OV:P1,P1,GSM642933_OC01_ARN0001_s1h1s1_U133p2.CEL.gz,GSM642933_OC01_ARN0001_s1h1s1_U133p2.CEL.gz,PreprocessedData_OV.xlsx,metabo_imputed_filtered_Tumor,MergedDeconvolution.GSE26193.csv,GSE26193.hgu133plus2.gene_symbol.csv,GSE26193.hgu133plus2.gene_symbol.csv,OV,HGSOC,Tumor,OV
221,PDAC:NCIA-01751,NCIA-01751,GSM1527201_Hussain_13_17530_HuGene.1_0.st.v1_....,GSM1527201_Hussain_13_17530_HuGene.1_0.st.v1_....,PreprocessedData_PDAC.xlsx,metabo_imputed_filtered_Normal,MergedDeconvolution.GSE62452.csv,GSE62452.hugene10st.gene_symbol.csv,GSE62452.hugene10st.gene_symbol.csv,PDAC,PDAC,Normal,PDAC
260,BRCA_Terunuma:499527,499527,GSM926965.CEL.gz,GSM926965.CEL.gz,PreprocessedData_BRCA1.xlsx,metabo_imputed_filtered_Normal,GSE37751.ssGSEA.UnNorm.Deconvolution.csv,GSE37751.hugene10st.gene_symbol.csv,GSE37751.hugene10st.gene_symbol.csv,BRCA1,Breast Cancer,Normal,BRCA_Terunuma
368,COAD:6N,6N,GSM2358437,GSM2358437,PreprocessedData_COAD.xlsx,metabo_imputed_filtered_Normal,MergedDeconvolution.GSE89076.csv,GSE89076.Agilent8x60K.log2_transformed.gene_sy...,GSE89076.Agilent8x60K.log2_transformed.gene_sy...,COAD,Colorectal Cancer,Normal,COAD
444,PRAD_2019A:DFCI-00502,DFCI-00502,X86_CAPT1831_8T.CEL,X86_CAPT1831_8T.CEL,PreprocessedData_PRAD.xlsx,metabo_imputed_filtered_Tumor,MergedDeconvolution.Cornell_PROSTATE.csv,Cornell_PROSTATE.BatchAdj.hugene20st.gene_symb...,Cornell_PROSTATE.BatchAdj.hugene20st.gene_symb...,PRAD,Prostate Adenocarcinoma,Tumor,PRAD_2019A
692,RC20:MSKC-00573,MSKC-00573,MSK1097,MSK1097,PreprocessedData_ccRCC4.xlsx,metabo_imputed_filtered_Tumor,Multiregions.2Batchs.ImmuneDeconvolution.csv,Multiregions.2Batchs.Sample.hg19KnownGene.tpm....,Multiregions.2Batchs.Sample.hg19KnownGene.raw....,ccRCC4,Clear Cell,Tumor,RC20
848,LiCa1:LCS_501,LCS_501,GSM1979367_A7_501A.CEL.gz,GSM1979367_A7_501A.CEL.gz,PreprocessedData_HCC.xlsx,metabo_imputed_filtered_Tumor,MergedDeconvolution.GSE76297.csv,GSE76297.hugene20st.gene_symbol.csv,GSE76297.hugene20st.gene_symbol.csv,HCC,Hepatocellular carcinoma,Tumor,LiCa1

In [7]:
import os


#Transcriptomics
directory_path = 'drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/pancancer_metabolomics_v.0.3.4/pancancer_metabolomics/data/transcriptomics_processed'
file_names = [f for f in os.listdir(directory_path) if os.path.isfile(os.path.join(directory_path, f))]

for file_i in file_names:
  print(file_i)

CPTAC_GBM_htseq_rna_04_09_2021.tpm.gene_symbol.csv
Cornell_DLBCL.tpm.gene_symbol.csv
GSE26193.hgu133plus2.gene_symbol.csv
GSE37751.hugene10st.gene_symbol.csv
GSE62452.hugene10st.gene_symbol.csv
GSE76297.hugene20st.gene_symbol.csv
MultiRegionalRCC.raw.gene_symbol.csv
MultiRegionalRCC.tpm.gene_symbol.csv
Project_08402_M.tpm.gene_symbol.csv
GSE89076.Agilent8x60K.log2_transformed.gene_symbol.csv
CPTAC_GBM_htseq_rna_04_09_2021.raw.gene_symbol.csv
Flow4Batch.raw.gene_symbol.csv
Cornell_DLBCL.raw.gene_symbol.csv
Flow4Batch.tpm.gene_symbol.csv
Cornell_PROSTATE.BatchAdj.hugene20st.gene_symbol.csv
Multiregions.2Batchs.Sample.hg19KnownGene.raw.gene_symbol.csv
PMC4187326_BRCA.raw.gene_symbol.csv
PMC4187326_BRCA.tpm.gene_symbol.csv
Project_08402_M.raw.gene_symbol.csv
HCC.raw.gene_symbol.csv
HCC.tpm.gene_symbol.csv
GSE28735.hugene10st.gene_symbol.csv
Multiregions.2Batchs.Sample.hg19KnownGene.tpm.gene_symbol.csv

In [8]:
#Metabolomics
directory_path = 'drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/pancancer_metabolomics_v.0.3.4/pancancer_metabolomics/data/metabolomics_processed'
file_names = [f for f in os.listdir(directory_path) if os.path.isfile(os.path.join(directory_path, f))]

for file_i in file_names:
  print(file_i)

PreprocessedData_BRCA2.xlsx
PreprocessedData_OV.xlsx
PreprocessedData_HCC.xlsx
PreprocessedData_ICC.xlsx
PreprocessedData_BRCA1.xlsx
PreprocessedData_COAD.xlsx
PreprocessedData_PDAC.xlsx
PreprocessedData_DLBCL.xlsx
PreprocessedData_ccRCC2.xlsx
PreprocessedData_ccRCC1.xlsx
PreprocessedData_GBM.xlsx
PreprocessedData_ccRCC3.xlsx
PreprocessedData_ccRCC4.xlsx
PreprocessedData_PRAD.xlsx
PreprocessedData_HurthleCC.xlsx

In [9]:
samples_dict = sample_annot_microarrays[["MetabFile", "RNAFile"]].set_index("RNAFile").to_dict()["MetabFile"]
samples_dict

{'GSE26193.hgu133plus2.gene_symbol.csv': 'PreprocessedData_OV.xlsx',
 'GSE62452.hugene10st.gene_symbol.csv': 'PreprocessedData_PDAC.xlsx',
 'GSE37751.hugene10st.gene_symbol.csv': 'PreprocessedData_BRCA1.xlsx',
 'GSE89076.Agilent8x60K.log2_transformed.gene_symbol.csv': 'PreprocessedData_COAD.xlsx',
 'Cornell_PROSTATE.BatchAdj.hugene20st.gene_symbol.csv': 'PreprocessedData_PRAD.xlsx',
 'Multiregions.2Batchs.Sample.hg19KnownGene.tpm.gene_symbol.csv': 'PreprocessedData_ccRCC4.xlsx',
 'GSE76297.hugene20st.gene_symbol.csv': 'PreprocessedData_HCC.xlsx'}

In [10]:
met_genes = pd.read_csv('drive/My Drive/Colab Notebooks/GP_lab_data/FBA_metabolic_atlas_models/human_gem_associated_genes.csv')
met_genes

              gene_id   Symbol
0     ENSG00000198712   MT-CO2
1     ENSG00000198804   MT-CO1
2     ENSG00000198938   MT-CO3
3     ENSG00000198899  MT-ATP6
4     ENSG00000198886   MT-ND4
...               ...      ...
2879  ENSG00000167751     KLK2
2880  ENSG00000129873    CDY2B
2881  ENSG00000182415    CDY2A
2882  ENSG00000172352    CDY1B
2883  ENSG00000172288     CDY1

[2884 rows x 2 columns]

In [11]:
import joblib

model = joblib.load('drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/Tissue_res/ElasticNet.pkl')
model_features = model.feature_names_in_
model_features

array(['ENSG00000198712', 'ENSG00000198804', 'ENSG00000198938', ...,
       'ENSG00000197838', 'ENSG00000167751', 'ENSG00000182415'],
      dtype=object)

In [12]:
import pickle

with open('drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/Tissue_res/y_train_features.pkl', 'rb') as file:
    y_features = pickle.load(file)

y_features = list(y_features)

In [13]:
def merge_data(dictionary):

  for sample_rna, sample_met in dictionary.items():

    #Gene expression
    rna = pd.read_csv(f'drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/pancancer_metabolomics_v.0.3.4/pancancer_metabolomics/data/transcriptomics_processed/{sample_rna}', index_col = 0)
    rna.index.name = None
    rna = rna.T
    met_genes_select = met_genes[met_genes['Symbol'].isin(rna.columns)]
    met_genes_select = met_genes_select.Symbol.to_list()
    rna = rna[met_genes_select]
    rna = rna.T
    rna = pd.concat([met_genes.set_index('Symbol'), rna], axis = 'columns')
    rna = rna.set_index('gene_id')
    rna.index.name = None
    rna = rna.T
    rna = rna.reindex(model_features, axis = 'columns')


    met_id = sample_annot[sample_annot['RNAFile'].isin(microarrays)]
    met_id = met_id[['RNAID', 'MetabID']]
    met_id = met_id.set_index('RNAID')
    met_id.index.name = None
    rna = pd.concat([met_id, rna], axis = 'columns')
    rna = rna.set_index('MetabID')

    file_name = sample_rna.split('.')[0]
    rna.to_csv(f'drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/Microarrays/{file_name}_gene_expression.csv')
    print(str(file_name)+ '_gene_expression.csv' + ' saved!')

    #Metabolomics
    cohort_metabolomics = samples_dict[sample_rna]
    metabolomics = pd.read_excel(f'drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/pancancer_metabolomics_v.0.3.4/pancancer_metabolomics/data/metabolomics_processed/{cohort_metabolomics}', index_col = 0)
    common_metabolites = list(set(y_features).intersection(metabolomics.index))
    metabolomics = metabolomics.loc[common_metabolites]
    metabolomics = metabolomics.T

    metabolomics.to_csv(f'drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/Microarrays/{file_name}_metabolomics.csv')
    print(str(file_name)+ '_metabolomics.csv' + ' saved!')

In [14]:
merge_data(samples_dict)

GSE26193_gene_expression.csv saved!
GSE26193_metabolomics.csv saved!
GSE62452_gene_expression.csv saved!
GSE62452_metabolomics.csv saved!
GSE37751_gene_expression.csv saved!
GSE37751_metabolomics.csv saved!
GSE89076_gene_expression.csv saved!
GSE89076_metabolomics.csv saved!
Cornell_PROSTATE_gene_expression.csv saved!
Cornell_PROSTATE_metabolomics.csv saved!
Multiregions_gene_expression.csv saved!
Multiregions_metabolomics.csv saved!
GSE76297_gene_expression.csv saved!
GSE76297_metabolomics.csv saved!