#Import modules

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

#Preparing metabolomics

In [3]:
import pickle

# Save the list to a file
with open('drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/Tissue_res/y_train_features.pkl', 'rb') as file:
    y_features = pickle.load(file)

y_features = list(y_features)

In [4]:
metabolite_names_train = pd.read_csv('drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/Tissue_res/y_train_tissue_name_map.csv')
metabolite_names_train = metabolite_names_train.dropna(subset = 'HMDB')
metabolite_names_train

,Query,Match,HMDB,PubChem,ChEBI,KEGG,METLIN,SMILES,Comment
5,1-linoleoyl-GPC (18:2),LysoPC(18:2/0:0),HMDB0010386,11005824.0,28733.0,C04230,NaN,CCCCC\C=C/C\C=C/CCCCCCCC(=O)OC[C@@H](O)COP([O-...,1
6,1-oleoylglycerol (1-monoolein),MG(18:1(9Z)/0:0/0:0),HMDB0011567,12178130.0,75757.0,NaN,NaN,[H][C@](O)(CO)COC(=O)CCCCCCC\C=C/CCCCCCCC,1
10,1-palmitoyl-GPC (16:0),LysoPC(16:0/0:0),HMDB0010382,460602.0,72998.0,C04230,NaN,CCCCCCCCCCCCCCCC(=O)OC[C@@H](O)COP([O-])(=O)OC...,1
11,1-palmitoyl-GPE (16:0),LysoPE(16:0/0:0),HMDB0011503,9547069.0,73004.0,NaN,NaN,[H][C@@](O)(COC(=O)CCCCCCCCCCCCCCC)COP(O)(=O)OCCN,1
16,10-heptadecenoate (17:1n7),10Z-Heptadecenoic acid,HMDB0060038,5312435.0,75094.0,NaN,NaN,CCCCCC\C=C/CCCCCCCCC(O)=O,1
...,...,...,...,...,...,...,...,...,...
213,xanthosine,Xanthosine,HMDB0000299,64959.0,18107.0,C01762,3408.0,OC[C@H]1O[C@H]([C@H](O)[C@@H]1O)N1C=NC2=C1N=C(...,1
214,3-phosphoglycerate,3-Phosphoglyceric acid,HMDB0000807,724.0,17050.0,C00597,150.0,OC(COP(O)(O)=O)C(O)=O,1
215,dehydroascorbate,Dehydroascorbic acid,HMDB0001264,440667.0,27956.0,C05422,342.0,[H][C@@]1(OC(=O)C(=O)C1=O)[C@@H](O)CO,1
216,pyruvate,Pyruvic acid,HMDB0000243,1060.0,32816.0,C00022,117.0,CC(=O)C(O)=O,1
217,phosphoenolpyruvate (PEP),Phosphoenolpyruvic acid,HMDB0000263,1005.0,44897.0,C00074,5264.0,OC(=O)C(=C)OP(O)(O)=O,1

In [5]:
metabolite_names_fudan = pd.read_csv('drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/Fudan_metabolite_name_map.csv')
metabolite_names_fudan = metabolite_names_fudan.dropna(subset = 'HMDB')
metabolite_names_fudan

,Query,Match,HMDB,PubChem,ChEBI,KEGG,METLIN,SMILES,Comment
118,PE (37:0),PE(15:0/22:0),HMDB0008907,52924172.0,134232,C00350,NaN,[H][C@@](COC(=O)CCCCCCCCCCCCCC)(COP(O)(=O)OCCN...,1
208,LPC (18:0),LysoPC(0:0/18:0),HMDB0011128,24779491.0,76076,NaN,NaN,CCCCCCCCCCCCCCCCCC(=O)O[C@H](CO)COP([O-])(=O)O...,1
1753,Adenosine,Adenosine,HMDB0000050,60961.0,16335,C00212,86.0,NC1=C2N=CN([C@@H]3O[C@H](CO)[C@@H](O)[C@H]3O)C...,1
1754,cis-9-Palmitoleic acid,Palmitoleic acid,HMDB0003229,445638.0,28716,C08362,188.0,CCCCCC\C=C/CCCCCCCC(O)=O,1
1755,Dihydroxyacetone,Dihydroxyacetone,HMDB0001882,670.0,16016,C00184,6368.0,OCC(=O)CO,1
...,...,...,...,...,...,...,...,...,...
2342,Adipic acid,Adipic acid,HMDB0000448,196.0,30832,C06104,115.0,OC(=O)CCCCC(O)=O,1
2343,Met-Gln,Methionyl-Glutamine,HMDB0028971,22935677.0,NaN,NaN,NaN,CSCCC(N)C(=O)NC(CCC(N)=O)C(O)=O,1
2344,Pristanic acid,Pristanic acid,HMDB0000795,123929.0,51340,NaN,5760.0,CC(C)CCCC(C)CCCC(C)CCCC(C)C(O)=O,1
2345,(Z)-6-Octadecenoic acid,petroselinate,HMDB0304458,5461010.0,32375,NaN,NaN,CCCCCCCCCCC\C=C/CCCCC([O-])=O,1
2346,Glycogen,Glycogen,HMDB0000757,439177.0,28087,C00182,160.0,OC[C@H]1O[C@H](OC[C@H]2O[C@H](O[C@H]3[C@H](O)[...,1

In [6]:
common_hmdb = list(set(metabolite_names_train['HMDB']).intersection(metabolite_names_fudan['HMDB']))
len(common_hmdb)

102

In [7]:
metabolite_names_train = metabolite_names_train[metabolite_names_train['HMDB'].isin(common_hmdb)]
metabolite_names_train.drop_duplicates(subset = 'HMDB', inplace = True)
metabolite_names_train

/tmp/ipython-input-2958471856.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metabolite_names_train.drop_duplicates(subset = 'HMDB', inplace = True)

,Query,Match,HMDB,PubChem,ChEBI,KEGG,METLIN,SMILES,Comment
10,1-palmitoyl-GPC (16:0),LysoPC(16:0/0:0),HMDB0010382,460602.0,72998.0,C04230,NaN,CCCCCCCCCCCCCCCC(=O)OC[C@@H](O)COP([O-])(=O)OC...,1
11,1-palmitoyl-GPE (16:0),LysoPE(16:0/0:0),HMDB0011503,9547069.0,73004.0,NaN,NaN,[H][C@@](O)(COC(=O)CCCCCCCCCCCCCCC)COP(O)(=O)OCCN,1
21,2'-deoxyinosine,Deoxyinosine,HMDB0000071,65058.0,28997.0,C05512,3383.0,OC[C@H]1O[C@H](C[C@@H]1O)N1C=NC2=C1N=CNC2=O,1
27,3-(4-hydroxyphenyl)lactate,Hydroxyphenyllactic acid,HMDB0000755,9378.0,17385.0,C03672,5723.0,OC(CC1=CC=C(O)C=C1)C(O)=O,1
30,3-hydroxybutyrate (BHBA),3-Hydroxybutyric acid,HMDB0000011,441.0,17066.0,C01089,NaN,C[C@@H](O)CC(O)=O,1
...,...,...,...,...,...,...,...,...,...
208,urea,Urea,HMDB0000294,1176.0,16199.0,C00086,6.0,NC(N)=O,1
209,uridine,Uridine,HMDB0000296,6029.0,16704.0,C00299,90.0,OC[C@H]1O[C@H]([C@H](O)[C@@H]1O)N1C=CC(=O)NC1=O,1
210,valine,L-Valine,HMDB0000883,6287.0,16414.0,C00183,5842.0,CC(C)[C@H](N)C(O)=O,1
213,xanthosine,Xanthosine,HMDB0000299,64959.0,18107.0,C01762,3408.0,OC[C@H]1O[C@H]([C@H](O)[C@@H]1O)N1C=NC2=C1N=C(...,1
216,pyruvate,Pyruvic acid,HMDB0000243,1060.0,32816.0,C00022,117.0,CC(=O)C(O)=O,1

In [8]:
metabolite_names_train_query_hmdb_dict = metabolite_names_train[['Query', 'HMDB']].set_index('Query').to_dict()['HMDB']
metabolite_names_train_query_hmdb_dict

{'1-palmitoyl-GPC (16:0)': 'HMDB0010382',
 '1-palmitoyl-GPE (16:0)': 'HMDB0011503',
 "2'-deoxyinosine": 'HMDB0000071',
 '3-(4-hydroxyphenyl)lactate': 'HMDB0000755',
 '3-hydroxybutyrate (BHBA)': 'HMDB0000011',
 '3-indoxyl sulfate': 'HMDB0000682',
 '4-methyl-2-oxopentanoate': 'HMDB0000695',
 '5-methylthioadenosine (MTA)': 'HMDB0001173',
 '5-oxoproline': 'HMDB0000267',
 '6-phosphogluconate': 'HMDB0001316',
 'acetylcarnitine': 'HMDB0000201',
 'adenine': 'HMDB0000034',
 'adenosine': 'HMDB0000050',
 'alanine': 'HMDB0000161',
 'alanylleucine': 'HMDB0028691',
 'anserine': 'HMDB0000194',
 'arginine': 'HMDB0000517',
 'asparagine': 'HMDB0000168',
 'aspartate': 'HMDB0000191',
 'beta-alanine': 'HMDB0000056',
 'betaine': 'HMDB0000043',
 'carnitine': 'HMDB0000062',
 'choline': 'HMDB0000097',
 'phosphocholine': 'HMDB0001565',
 'citrate': 'HMDB0000094',
 'citrulline': 'HMDB0000904',
 'creatine': 'HMDB0000064',
 'creatinine': 'HMDB0000562',
 'cytidine': 'HMDB0000089',
 'ergothioneine': 'HMDB0003045',
 'erythritol': 'HMDB0002994',
 'fructose': 'HMDB0000660',
 'fumarate': 'HMDB0000134',
 'gamma-glutamylglutamate': 'HMDB0011737',
 'gamma-glutamylphenylalanine': 'HMDB0000594',
 'gamma-glutamylvaline': 'HMDB0011172',
 'gluconate': 'HMDB0000625',
 'glutamate': 'HMDB0000148',
 'glutamine': 'HMDB0000641',
 'glutathione, oxidized (GSSG)': 'HMDB0003337',
 'glutathione, reduced (GSH)': 'HMDB0000125',
 'glycerate': 'HMDB0000139',
 'glycerol': 'HMDB0000131',
 'glycerol 3-phosphate (G3P)': 'HMDB0000126',
 'glycerophosphorylcholine (GPC)': 'HMDB0000086',
 'glycine': 'HMDB0000123',
 'glycylleucine': 'HMDB0000759',
 'guanosine': 'HMDB0000133',
 'hippurate': 'HMDB0000714',
 'histamine': 'HMDB0000870',
 'histidine': 'HMDB0000177',
 'hypoxanthine': 'HMDB0000157',
 'inosine': 'HMDB0000195',
 'kynurenine': 'HMDB0000684',
 'laurate (12:0)': 'HMDB0000638',
 'leucine': 'HMDB0000687',
 'linoleate (18:2n6)': 'HMDB0000673',
 'lysine': 'HMDB0000182',
 'malate': 'HMDB0000156',
 'maltose': 'HMDB0000163',
 'maltotriose': 'HMDB0001262',
 'mannose': 'HMDB0000169',
 'margarate (17:0)': 'HMDB0002259',
 'methionine': 'HMDB0000696',
 'myo-inositol': 'HMDB0000211',
 'myristate (14:0)': 'HMDB0000806',
 'myristoleate (14:1n5)': 'HMDB0002000',
 'N-acetylalanine': 'HMDB0000766',
 'N-acetylaspartate (NAA)': 'HMDB0000812',
 'N-acetylglycine': 'HMDB0000532',
 'nicotinamide': 'HMDB0001406',
 'ornithine': 'HMDB0000214',
 'palmitate (16:0)': 'HMDB0000220',
 'palmitoleate (16:1n7)': 'HMDB0003229',
 'pantothenate': 'HMDB0000210',
 'pentadecanoate (15:0)': 'HMDB0000826',
 'phenylacetylglutamine': 'HMDB0006344',
 'phenylalanine': 'HMDB0000159',
 'phosphoethanolamine': 'HMDB0000224',
 'proline': 'HMDB0000162',
 'pseudouridine': 'HMDB0000767',
 'ribose': 'HMDB0000283',
 'S-adenosylhomocysteine (SAH)': 'HMDB0000939',
 'serine': 'HMDB0000187',
 'sphingosine': 'HMDB0000252',
 'stearate (18:0)': 'HMDB0000827',
 'stearoyl sphingomyelin (d18:1/18:0)': 'HMDB0001348',
 'stearoylcarnitine': 'HMDB0000848',
 'succinate': 'HMDB0000254',
 'taurine': 'HMDB0000251',
 'threonate': 'HMDB0000943',
 'threonine': 'HMDB0000167',
 'thymine': 'HMDB0000262',
 'tryptophan': 'HMDB0000929',
 'tyrosine': 'HMDB0000158',
 'uracil': 'HMDB0000300',
 'urate': 'HMDB0000289',
 'urea': 'HMDB0000294',
 'uridine': 'HMDB0000296',
 'valine': 'HMDB0000883',
 'xanthosine': 'HMDB0000299',
 'pyruvate': 'HMDB0000243'}

In [9]:
with open('drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/Tissue_res/Fudan_data_processed/y_train_features_fudan_hmdb_common.pkl', 'wb') as file:
    pickle.dump(metabolite_names_train_query_hmdb_dict, file)

In [10]:
metabolite_names_fudan = metabolite_names_fudan[metabolite_names_fudan['HMDB'].isin(common_hmdb)]
metabolite_names_fudan

,Query,Match,HMDB,PubChem,ChEBI,KEGG,METLIN,SMILES,Comment
1753,Adenosine,Adenosine,HMDB0000050,60961.0,16335,C00212,86.0,NC1=C2N=CN([C@@H]3O[C@H](CO)[C@@H](O)[C@H]3O)C...,1
1754,cis-9-Palmitoleic acid,Palmitoleic acid,HMDB0003229,445638.0,28716,C08362,188.0,CCCCCC\C=C/CCCCCCCC(O)=O,1
1757,Palmitic acid,Palmitic acid,HMDB0000220,985.0,15756,C00249,187.0,CCCCCCCCCCCCCCCC(O)=O,1
1761,Ornithine,Ornithine,HMDB0000214,6262.0,15729,C00077,27.0,NCCC[C@H](N)C(O)=O,1
1763,S-Methyl-5'-thioadenosine,5'-Methylthioadenosine,HMDB0001173,439176.0,17509,C00170,3425.0,CSC[C@H]1O[C@H]([C@H](O)[C@@H]1O)N1C=NC2=C1N=C...,1
...,...,...,...,...,...,...,...,...,...
2236,Citrate,Citric acid,HMDB0000094,311.0,30769,C00158,124.0,OC(=O)CC(O)(CC(O)=O)C(O)=O,1
2244,L-Anserine,Anserine,HMDB0000194,112072.0,18323,C01262,5209.0,CN1C=NC=C1C[C@H](NC(=O)CCN)C(O)=O,1
2324,Erythritol,Erythritol,HMDB0002994,222285.0,17113,C00503,140.0,OC[C@H](O)[C@H](O)CO,1
2326,Glutathione,Glutathione,HMDB0000125,124886.0,16856,C00051,44.0,N[C@@H](CCC(=O)N[C@@H](CS)C(=O)NCC(O)=O)C(O)=O,1
2330,Beta-Alanine,beta-Alanine,HMDB0000056,239.0,16958,C00099,5119.0,NCCC(O)=O,1

In [11]:
lipids = pd.read_csv('drive/My Drive/Colab Notebooks/GP_lab_data/BRCA1_project/Fudan_TripleNegative/FUSCC_TNBC_LipidMets.csv', index_col = 1, skiprows = 1)
lipids = lipids.drop('Peak', axis = 'columns')
lipids.index.name = None
lipids

,FUSCCTNBC002_T,FUSCCTNBC049_T,FUSCCTNBC053_T,FUSCCTNBC060_T,FUSCCTNBC061_T,FUSCCTNBC064_T,FUSCCTNBC074_T,FUSCCTNBC082_T,FUSCCTNBC089_T,FUSCCTNBC094_T,...,FUSCCTNBC295_N,FUSCCTNBC041_N,FUSCCTNBC275_N,FUSCCTNBC118_N,FUSCCTNBC443_N,FUSCCTNBC100_N,FUSCCTNBC057_N,FUSCCTNBC252_N,FUSCCTNBC068_N,FUSCCTNBC220_N
FA (16:0),15.388690,16.321576,14.803728,15.501837,15.438272,14.344296,14.385323,16.129686,14.919981,15.070121,...,15.451211,15.276851,15.451211,15.717998,15.078484,15.931569,15.364955,14.910643,15.095067,14.933875
FA (18:1),13.910643,14.323336,12.390706,13.302068,13.731319,12.720672,12.157978,14.323336,12.855258,12.978353,...,14.001408,14.677279,14.221285,14.526499,14.251186,13.489346,14.655083,13.666224,13.741888,14.574594
FA (18:2),12.056638,12.179909,11.029287,11.409391,11.565102,10.764872,9.876517,13.476746,11.516685,9.906891,...,12.906891,14.001408,13.124444,13.501837,12.921841,12.032735,13.823765,12.167418,12.538674,13.257093
FA (19:0),9.011227,0.978196,12.388017,0.321928,0.782409,12.056638,11.506803,-0.092340,12.412041,16.335600,...,-0.601650,-0.671164,-0.486004,0.014355,-0.727380,0.956057,-0.516636,10.980140,-0.270556,-0.673463
FA (20:4),12.201511,11.276124,11.560333,11.611947,11.670656,12.506803,12.287712,10.276124,11.355351,11.496854,...,9.049849,9.111136,10.550747,8.675957,9.722808,10.837628,8.417853,10.430453,10.643856,10.022368
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
FAHFA (41:7),11.598052,8.885696,12.176796,8.636625,9.611025,11.360847,11.857203,8.727920,11.451211,10.853310,...,7.754888,7.894818,8.519636,7.826548,8.087463,8.169925,7.098032,8.366322,8.622052,7.228819
FAHFA (35:4),9.335390,9.167418,11.884171,7.348728,9.625709,10.142107,11.186114,9.076816,10.398744,11.516685,...,8.005625,7.707359,7.066089,8.233620,7.507795,9.226412,7.554589,8.643856,8.710806,7.577429
PMeOH (49:4),12.349834,13.762797,13.598052,14.213712,13.412041,13.186114,12.506803,14.309192,14.813781,13.773139,...,14.251186,16.529553,15.232571,15.425216,14.405407,15.773139,14.392049,14.813781,15.018896,15.865443
Cer-EODS (50:1),6.292782,6.658211,7.577429,7.375039,6.589464,8.055282,7.459432,10.252665,8.527477,7.781360,...,9.301496,12.363587,11.914385,11.287712,10.781360,9.705632,11.910643,9.908393,11.049849,11.501837
SM (51:2),13.058330,13.451211,12.479275,13.385323,13.872675,13.189207,13.078484,13.096715,12.073472,13.073472,...,12.113091,12.347068,12.750288,13.183015,12.293472,14.010178,12.675075,11.630267,12.891784,12.600378

In [12]:
lipids.columns = lipids.columns.str.replace(r'_T$', '', regex=True)

In [13]:
lipids.head(3)

,FUSCCTNBC002,FUSCCTNBC049,FUSCCTNBC053,FUSCCTNBC060,FUSCCTNBC061,FUSCCTNBC064,FUSCCTNBC074,FUSCCTNBC082,FUSCCTNBC089,FUSCCTNBC094,...,FUSCCTNBC295_N,FUSCCTNBC041_N,FUSCCTNBC275_N,FUSCCTNBC118_N,FUSCCTNBC443_N,FUSCCTNBC100_N,FUSCCTNBC057_N,FUSCCTNBC252_N,FUSCCTNBC068_N,FUSCCTNBC220_N
FA (16:0),15.388690,16.321576,14.803728,15.501837,15.438272,14.344296,14.385323,16.129686,14.919981,15.070121,...,15.451211,15.276851,15.451211,15.717998,15.078484,15.931569,15.364955,14.910643,15.095067,14.933875
FA (18:1),13.910643,14.323336,12.390706,13.302068,13.731319,12.720672,12.157978,14.323336,12.855258,12.978353,...,14.001408,14.677279,14.221285,14.526499,14.251186,13.489346,14.655083,13.666224,13.741888,14.574594
FA (18:2),12.056638,12.179909,11.029287,11.409391,11.565102,10.764872,9.876517,13.476746,11.516685,9.906891,...,12.906891,14.001408,13.124444,13.501837,12.921841,12.032735,13.823765,12.167418,12.538674,13.257093

In [14]:
polar_mets = pd.read_csv('drive/My Drive/Colab Notebooks/GP_lab_data/BRCA1_project/Fudan_TripleNegative/FUSCC_TNBC_PolarMets.csv', index_col = 1, skiprows = 1)
polar_mets = polar_mets.drop('Peak', axis = 'columns')
polar_mets.index.name = None
polar_mets

,FUSCCTNBC002_T,FUSCCTNBC049_T,FUSCCTNBC053_T,FUSCCTNBC060_T,FUSCCTNBC061_T,FUSCCTNBC064_T,FUSCCTNBC074_T,FUSCCTNBC082_T,FUSCCTNBC089_T,FUSCCTNBC094_T,...,FUSCCTNBC295_N,FUSCCTNBC041_N,FUSCCTNBC275_N,FUSCCTNBC118_N,FUSCCTNBC443_N,FUSCCTNBC100_N,FUSCCTNBC057_N,FUSCCTNBC252_N,FUSCCTNBC068_N,FUSCCTNBC220_N
Adenosine,21.291669,22.449926,23.202486,22.470636,22.773308,23.977096,22.931306,20.220963,21.955768,23.272642,...,20.834784,21.319542,20.569985,20.556202,21.114652,21.764207,20.592852,18.964724,21.215000,18.871322
cis-9-Palmitoleic acid,17.379201,16.339084,17.216357,16.215609,17.616161,15.677279,17.536460,17.468027,16.775585,15.589300,...,16.802945,17.384143,16.511135,17.008877,16.735530,16.881198,16.970218,17.817633,16.183015,16.254881
Dihydroxyacetone,17.197994,17.402221,15.206099,18.050540,13.919981,15.879870,14.574594,17.779880,16.520373,16.705862,...,17.534098,18.163099,18.085732,18.362838,17.506974,18.157021,18.655405,16.923177,18.159817,18.454765
Adenosine monophosphate (AMP),17.368600,16.074309,19.518467,15.565697,20.635271,18.166953,18.793702,14.638210,15.495605,19.907728,...,13.598052,14.818782,15.447987,13.709945,15.823765,17.019634,13.501837,19.028370,16.139711,12.122828
Palmitic acid,19.533546,19.881713,19.696190,20.109475,19.755466,19.438148,19.742342,20.675572,19.650007,18.698962,...,20.238028,20.369183,20.342075,19.888779,20.311458,20.037044,20.405553,20.577451,20.249903,20.215464
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Adipic acid,14.111462,13.655083,12.299208,13.666224,14.514221,13.813781,15.333854,13.385323,15.213712,12.237807,...,14.412041,14.228819,13.666224,14.316282,14.198445,13.476746,14.294908,14.273213,13.853310,14.151651
Met-Gln,12.039605,12.681678,10.731319,12.724940,12.718533,13.803728,13.586371,12.349834,12.683872,11.167418,...,13.271755,12.960364,13.201511,13.010178,12.516685,12.910643,13.003167,12.304922,12.731319,13.075145
Pristanic acid,15.699139,14.736613,16.643800,15.036174,16.038319,14.956739,15.498725,17.085213,16.416995,14.550747,...,16.155609,15.194603,15.074309,16.954185,16.253035,16.763173,16.294908,17.212753,15.860602,18.455118
(Z)-6-Octadecenoic acid,15.621136,15.547738,13.974773,15.053247,13.793603,14.183015,13.330357,15.677279,14.858175,11.857203,...,15.526499,15.635378,16.038319,14.767978,15.887030,15.151651,15.444756,16.044736,16.206099,15.726005
Glycogen,11.404077,1.855990,11.727070,2.316146,10.891784,9.726218,11.466586,2.046142,11.419960,12.803728,...,2.528571,2.341986,2.518535,2.541019,2.153805,2.378512,2.691534,2.715893,2.469886,2.632268

In [15]:
polar_mets.columns = polar_mets.columns.str.replace(r'_T$', '', regex=True)
polar_mets.head(3)

,FUSCCTNBC002,FUSCCTNBC049,FUSCCTNBC053,FUSCCTNBC060,FUSCCTNBC061,FUSCCTNBC064,FUSCCTNBC074,FUSCCTNBC082,FUSCCTNBC089,FUSCCTNBC094,...,FUSCCTNBC295_N,FUSCCTNBC041_N,FUSCCTNBC275_N,FUSCCTNBC118_N,FUSCCTNBC443_N,FUSCCTNBC100_N,FUSCCTNBC057_N,FUSCCTNBC252_N,FUSCCTNBC068_N,FUSCCTNBC220_N
Adenosine,21.291669,22.449926,23.202486,22.470636,22.773308,23.977096,22.931306,20.220963,21.955768,23.272642,...,20.834784,21.319542,20.569985,20.556202,21.114652,21.764207,20.592852,18.964724,21.215000,18.871322
cis-9-Palmitoleic acid,17.379201,16.339084,17.216357,16.215609,17.616161,15.677279,17.536460,17.468027,16.775585,15.589300,...,16.802945,17.384143,16.511135,17.008877,16.735530,16.881198,16.970218,17.817633,16.183015,16.254881
Dihydroxyacetone,17.197994,17.402221,15.206099,18.050540,13.919981,15.879870,14.574594,17.779880,16.520373,16.705862,...,17.534098,18.163099,18.085732,18.362838,17.506974,18.157021,18.655405,16.923177,18.159817,18.454765

In [16]:
metabolites = pd.concat([lipids, polar_mets], axis = 'index')
metabolites

,FUSCCTNBC002,FUSCCTNBC049,FUSCCTNBC053,FUSCCTNBC060,FUSCCTNBC061,FUSCCTNBC064,FUSCCTNBC074,FUSCCTNBC082,FUSCCTNBC089,FUSCCTNBC094,...,FUSCCTNBC295_N,FUSCCTNBC041_N,FUSCCTNBC275_N,FUSCCTNBC118_N,FUSCCTNBC443_N,FUSCCTNBC100_N,FUSCCTNBC057_N,FUSCCTNBC252_N,FUSCCTNBC068_N,FUSCCTNBC220_N
FA (16:0),15.388690,16.321576,14.803728,15.501837,15.438272,14.344296,14.385323,16.129686,14.919981,15.070121,...,15.451211,15.276851,15.451211,15.717998,15.078484,15.931569,15.364955,14.910643,15.095067,14.933875
FA (18:1),13.910643,14.323336,12.390706,13.302068,13.731319,12.720672,12.157978,14.323336,12.855258,12.978353,...,14.001408,14.677279,14.221285,14.526499,14.251186,13.489346,14.655083,13.666224,13.741888,14.574594
FA (18:2),12.056638,12.179909,11.029287,11.409391,11.565102,10.764872,9.876517,13.476746,11.516685,9.906891,...,12.906891,14.001408,13.124444,13.501837,12.921841,12.032735,13.823765,12.167418,12.538674,13.257093
FA (19:0),9.011227,0.978196,12.388017,0.321928,0.782409,12.056638,11.506803,-0.092340,12.412041,16.335600,...,-0.601650,-0.671164,-0.486004,0.014355,-0.727380,0.956057,-0.516636,10.980140,-0.270556,-0.673463
FA (20:4),12.201511,11.276124,11.560333,11.611947,11.670656,12.506803,12.287712,10.276124,11.355351,11.496854,...,9.049849,9.111136,10.550747,8.675957,9.722808,10.837628,8.417853,10.430453,10.643856,10.022368
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Adipic acid,14.111462,13.655083,12.299208,13.666224,14.514221,13.813781,15.333854,13.385323,15.213712,12.237807,...,14.412041,14.228819,13.666224,14.316282,14.198445,13.476746,14.294908,14.273213,13.853310,14.151651
Met-Gln,12.039605,12.681678,10.731319,12.724940,12.718533,13.803728,13.586371,12.349834,12.683872,11.167418,...,13.271755,12.960364,13.201511,13.010178,12.516685,12.910643,13.003167,12.304922,12.731319,13.075145
Pristanic acid,15.699139,14.736613,16.643800,15.036174,16.038319,14.956739,15.498725,17.085213,16.416995,14.550747,...,16.155609,15.194603,15.074309,16.954185,16.253035,16.763173,16.294908,17.212753,15.860602,18.455118
(Z)-6-Octadecenoic acid,15.621136,15.547738,13.974773,15.053247,13.793603,14.183015,13.330357,15.677279,14.858175,11.857203,...,15.526499,15.635378,16.038319,14.767978,15.887030,15.151651,15.444756,16.044736,16.206099,15.726005
Glycogen,11.404077,1.855990,11.727070,2.316146,10.891784,9.726218,11.466586,2.046142,11.419960,12.803728,...,2.528571,2.341986,2.518535,2.541019,2.153805,2.378512,2.691534,2.715893,2.469886,2.632268

In [17]:
metabolites = metabolites.T
metabolites.head(3)

,FA (16:0),FA (18:1),FA (18:2),FA (19:0),FA (20:4),FA (21:0),FA (21:1),FA (21:2),FA (22:0),FA (22:5),...,Indole-3-carboxylic acid,Bumetanide,Synephrine,D-Erythrose 4-phosphate,"3,4-Dihydroxyhydrocinnamic acid",Adipic acid,Met-Gln,Pristanic acid,(Z)-6-Octadecenoic acid,Glycogen
FUSCCTNBC002,15.388690,13.910643,12.056638,9.011227,12.201511,9.663558,11.349834,10.321928,14.520373,11.281930,...,12.008429,12.496854,14.175238,9.820179,11.419960,14.111462,12.039605,15.699139,15.621136,11.404077
FUSCCTNBC049,16.321576,14.323336,12.179909,0.978196,11.276124,6.870365,7.679480,6.714246,13.165849,10.550747,...,11.466586,14.111462,14.251186,11.864960,15.945352,13.655083,12.681678,14.736613,15.547738,1.855990
FUSCCTNBC053,14.803728,12.390706,11.029287,12.388017,11.560333,13.891784,12.811776,11.880349,16.169377,11.276124,...,12.574594,12.369052,14.213712,10.240791,10.598052,12.299208,10.731319,16.643800,13.974773,11.727070

In [18]:
desired_metabolites = metabolite_names_fudan['Query'].tolist()
metabolites = metabolites[desired_metabolites]
metabolites

,Adenosine,cis-9-Palmitoleic acid,Palmitic acid,Ornithine,S-Methyl-5'-thioadenosine,Cytidine,L-Alanine,S-Adenosyl-L-homocysteine,Glycerol 3-phosphate,L-Methionine,...,Acetylglycine,Hippuric acid,gamma-L-Glutamyl-L-valine,Pyruvate,(R)-3-Hydroxybutyric acid,Citrate,L-Anserine,Erythritol,Glutathione,Beta-Alanine
FUSCCTNBC002,21.291669,17.379201,19.533546,14.752381,17.281514,13.438272,15.498725,15.460840,17.108708,18.389594,...,15.014544,16.147682,14.095067,19.686661,11.607330,15.498725,15.209910,17.454026,14.036174,12.963980
FUSCCTNBC049,22.449926,16.339084,19.881713,14.788514,19.866545,13.159556,15.739253,15.798674,14.671762,18.054933,...,14.693705,13.076816,13.666224,20.624987,13.371777,16.040461,14.952195,14.508042,13.938477,12.983706
FUSCCTNBC053,23.202486,17.216357,19.696190,14.371777,17.997979,14.010178,14.970286,16.732366,14.027560,18.714715,...,14.747144,12.264443,14.609640,21.766542,11.264443,16.055367,14.778283,11.903129,14.103288,12.593391
FUSCCTNBC060,22.470636,16.215609,20.109475,16.133704,18.747767,13.872675,16.031873,15.855744,15.247483,18.138002,...,13.699139,14.720672,13.666224,20.864579,13.024101,16.395400,13.992584,15.798674,14.258566,12.967587
FUSCCTNBC061,22.773308,17.616161,19.755466,16.446373,20.537163,14.143702,14.344296,15.646671,17.253183,18.775350,...,16.169377,17.936161,16.866820,21.061099,13.168985,17.718038,14.036174,12.576957,10.987264,13.091766
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
FUSCCTNBC100_N,21.764207,16.881198,20.037044,16.145693,2.378512,13.138912,15.457637,14.773139,14.988152,18.232852,...,13.938477,16.962738,12.246741,20.862873,14.919981,16.473579,14.309192,14.838613,13.451211,13.586371
FUSCCTNBC057_N,20.592852,16.970218,20.405553,16.080568,18.882330,13.501837,15.723341,15.660664,9.324181,17.181570,...,2.691534,16.589300,10.569856,20.332841,13.803728,16.982459,11.316282,14.660664,13.344296,12.987264
FUSCCTNBC252_N,18.964724,17.817633,20.577451,15.589300,2.715893,12.859146,14.580494,13.853310,14.747144,14.470405,...,12.912515,12.956739,12.240791,20.039388,12.943980,17.606644,13.992584,12.369052,2.715893,2.715893
FUSCCTNBC068_N,21.215000,16.183015,20.249903,15.912983,18.598798,13.699139,15.693705,15.111462,12.225810,17.796990,...,2.469886,13.249706,12.655083,20.496816,13.148477,16.512679,14.905951,14.258566,13.688250,12.819780
FUSCCTNBC220_N,18.871322,16.254881,20.215464,16.500282,2.632268,12.471675,15.780847,13.910643,14.036174,16.988174,...,9.611025,17.941414,11.419960,22.055089,13.268834,17.058658,12.109831,13.762797,13.039605,14.095067

In [19]:
metabolite_names_fudan_query_hmdb_dict = metabolite_names_fudan[['Query', 'HMDB']].set_index('Query').to_dict()['HMDB']
metabolite_names_fudan_query_hmdb_dict

{'Adenosine': 'HMDB0000050',
 'cis-9-Palmitoleic acid': 'HMDB0003229',
 'Palmitic acid': 'HMDB0000220',
 'Ornithine': 'HMDB0000214',
 "S-Methyl-5'-thioadenosine": 'HMDB0001173',
 'Cytidine': 'HMDB0000089',
 'L-Alanine': 'HMDB0000161',
 'S-Adenosyl-L-homocysteine': 'HMDB0000939',
 'Glycerol 3-phosphate': 'HMDB0000126',
 'L-Methionine': 'HMDB0000696',
 'L-Proline': 'HMDB0000162',
 'Urea': 'HMDB0000294',
 'Myristic acid': 'HMDB0000806',
 'Acetylcarnitine': 'HMDB0000201',
 'L-Arginine': 'HMDB0000517',
 'Linoleic acid': 'HMDB0000673',
 'Nicotinamide': 'HMDB0001406',
 'Phosphorylcholine': 'HMDB0001565',
 'Guanosine': 'HMDB0000133',
 'L-Glutamine': 'HMDB0000641',
 'L-Phenylalanine': 'HMDB0000159',
 'Stearoylcarnitine': 'HMDB0000848',
 'Uridine': 'HMDB0000296',
 'Maltotriose': 'HMDB0001262',
 'Sphingomyelin (d18:1/18:0)': 'HMDB0001348',
 'Taurine': 'HMDB0000251',
 'Uracil': 'HMDB0000300',
 'Hypoxanthine': 'HMDB0000157',
 'gamma-L-Glutamyl-L-glutamic acid': 'HMDB0011737',
 'D-Mannose': 'HMDB0000169',
 'Glutathione disulfide': 'HMDB0003337',
 'Adenine': 'HMDB0000034',
 'Inosine': 'HMDB0000195',
 'L-Glutamate': 'HMDB0000148',
 'O-Phosphoethanolamine': 'HMDB0000224',
 'L-Citrulline': 'HMDB0000904',
 'L-Kynurenine': 'HMDB0000684',
 'Glycerophosphocholine': 'HMDB0000086',
 'L-Histidine': 'HMDB0000177',
 'Dodecanoic acid': 'HMDB0000638',
 'L-Tyrosine': 'HMDB0000158',
 'L-Pyroglutamic acid': 'HMDB0000267',
 'Stearic acid': 'HMDB0000827',
 '1-Palmitoyl-2-hydroxy-sn-glycero-3-phosphoethanolamine': 'HMDB0011503',
 'L-Threonine': 'HMDB0000167',
 'L-Tryptophan': 'HMDB0000929',
 'Succinate': 'HMDB0000254',
 'Betaine': 'HMDB0000043',
 'Histamine': 'HMDB0000870',
 'Creatine': 'HMDB0000064',
 'Deoxyinosine': 'HMDB0000071',
 '1-Palmitoyl-sn-glycero-3-phosphocholine': 'HMDB0010382',
 'Ergothioneine': 'HMDB0003045',
 'D-gluconate': 'HMDB0000625',
 'N-Acetyl-L-aspartic acid': 'HMDB0000812',
 'L-Asparagine': 'HMDB0000168',
 'Leu-Gly': 'HMDB0000759',
 'Heptadecanoic acid': 'HMDB0002259',
 'L-Aspartate': 'HMDB0000191',
 'L-Threonate': 'HMDB0000943',
 'L-Lysine': 'HMDB0000182',
 'L-Valine': 'HMDB0000883',
 'Alpha-N-Phenylacetyl-L-glutamine': 'HMDB0006344',
 'Glycine': 'HMDB0000123',
 'myo-Inositol': 'HMDB0000211',
 'Indoxyl sulfate': 'HMDB0000682',
 'L-Serine': 'HMDB0000187',
 'L-Carnitine': 'HMDB0000062',
 'gamma-L-Glutamyl-L-phenylalanine': 'HMDB0000594',
 'L-Leucine': 'HMDB0000687',
 'L-Malic acid': 'HMDB0000156',
 'Hydroxyphenyllactic acid': 'HMDB0000755',
 'Pseudouridine': 'HMDB0000767',
 'Pantothenate': 'HMDB0000210',
 'Ala-Leu': 'HMDB0028691',
 'Glycerol': 'HMDB0000131',
 'Xanthosine': 'HMDB0000299',
 'Thymine': 'HMDB0000262',
 'D-Maltose': 'HMDB0000163',
 'Sphingosine': 'HMDB0000252',
 'Glyceric acid': 'HMDB0000139',
 'Myristoleic acid': 'HMDB0002000',
 'ketoisocaproic acid': 'HMDB0000695',
 '6-Phospho-D-gluconate': 'HMDB0001316',
 'D-Ribose': 'HMDB0000283',
 'Creatinine': 'HMDB0000562',
 'Uric acid': 'HMDB0000289',
 'D-Fructose': 'HMDB0000660',
 'Choline': 'HMDB0000097',
 'Fumarate': 'HMDB0000134',
 'N-Acetyl-L-alanine': 'HMDB0000766',
 'Pentadecanoic Acid': 'HMDB0000826',
 'Acetylglycine': 'HMDB0000532',
 'Hippuric acid': 'HMDB0000714',
 'gamma-L-Glutamyl-L-valine': 'HMDB0011172',
 'Pyruvate': 'HMDB0000243',
 '(R)-3-Hydroxybutyric acid': 'HMDB0000011',
 'Citrate': 'HMDB0000094',
 'L-Anserine': 'HMDB0000194',
 'Erythritol': 'HMDB0002994',
 'Glutathione': 'HMDB0000125',
 'Beta-Alanine': 'HMDB0000056'}

In [20]:
metabolites_columns = []
for col in metabolites.columns:
  metabolites_columns.append(metabolite_names_fudan_query_hmdb_dict[col])
metabolites.columns = metabolites_columns
metabolites

,HMDB0000050,HMDB0003229,HMDB0000220,HMDB0000214,HMDB0001173,HMDB0000089,HMDB0000161,HMDB0000939,HMDB0000126,HMDB0000696,...,HMDB0000532,HMDB0000714,HMDB0011172,HMDB0000243,HMDB0000011,HMDB0000094,HMDB0000194,HMDB0002994,HMDB0000125,HMDB0000056
FUSCCTNBC002,21.291669,17.379201,19.533546,14.752381,17.281514,13.438272,15.498725,15.460840,17.108708,18.389594,...,15.014544,16.147682,14.095067,19.686661,11.607330,15.498725,15.209910,17.454026,14.036174,12.963980
FUSCCTNBC049,22.449926,16.339084,19.881713,14.788514,19.866545,13.159556,15.739253,15.798674,14.671762,18.054933,...,14.693705,13.076816,13.666224,20.624987,13.371777,16.040461,14.952195,14.508042,13.938477,12.983706
FUSCCTNBC053,23.202486,17.216357,19.696190,14.371777,17.997979,14.010178,14.970286,16.732366,14.027560,18.714715,...,14.747144,12.264443,14.609640,21.766542,11.264443,16.055367,14.778283,11.903129,14.103288,12.593391
FUSCCTNBC060,22.470636,16.215609,20.109475,16.133704,18.747767,13.872675,16.031873,15.855744,15.247483,18.138002,...,13.699139,14.720672,13.666224,20.864579,13.024101,16.395400,13.992584,15.798674,14.258566,12.967587
FUSCCTNBC061,22.773308,17.616161,19.755466,16.446373,20.537163,14.143702,14.344296,15.646671,17.253183,18.775350,...,16.169377,17.936161,16.866820,21.061099,13.168985,17.718038,14.036174,12.576957,10.987264,13.091766
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
FUSCCTNBC100_N,21.764207,16.881198,20.037044,16.145693,2.378512,13.138912,15.457637,14.773139,14.988152,18.232852,...,13.938477,16.962738,12.246741,20.862873,14.919981,16.473579,14.309192,14.838613,13.451211,13.586371
FUSCCTNBC057_N,20.592852,16.970218,20.405553,16.080568,18.882330,13.501837,15.723341,15.660664,9.324181,17.181570,...,2.691534,16.589300,10.569856,20.332841,13.803728,16.982459,11.316282,14.660664,13.344296,12.987264
FUSCCTNBC252_N,18.964724,17.817633,20.577451,15.589300,2.715893,12.859146,14.580494,13.853310,14.747144,14.470405,...,12.912515,12.956739,12.240791,20.039388,12.943980,17.606644,13.992584,12.369052,2.715893,2.715893
FUSCCTNBC068_N,21.215000,16.183015,20.249903,15.912983,18.598798,13.699139,15.693705,15.111462,12.225810,17.796990,...,2.469886,13.249706,12.655083,20.496816,13.148477,16.512679,14.905951,14.258566,13.688250,12.819780
FUSCCTNBC220_N,18.871322,16.254881,20.215464,16.500282,2.632268,12.471675,15.780847,13.910643,14.036174,16.988174,...,9.611025,17.941414,11.419960,22.055089,13.268834,17.058658,12.109831,13.762797,13.039605,14.095067

In [37]:
metabolites.to_csv('drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/Tissue_res/Fudan_data_processed/metabolites_fudan_hmdb.csv', index = True)

#Preparing RNA seq

In [22]:
counts = pd.read_csv('drive/My Drive/Colab Notebooks/GP_lab_data/BRCA1_project/Fudan_TripleNegative/mRNA_counts_hgncsymbol.txt', sep = '\t')
counts = counts.rename(columns = {'Unnamed: 0' : 'Symbol'})
counts

,Symbol,FUSCCTNBC182,FUSCCTNBC203,FUSCCTNBC202,FUSCCTNBC252,FUSCCTNBC187,FUSCCTNBC303,FUSCCTNBC247,FUSCCTNBC285,FUSCCTNBC131,...,FUSCCTNBC473,FUSCCTNBC474,FUSCCTNBC471,FUSCCTNBC472,FUSCCTNBC477,FUSCCTNBC478,FUSCCTNBC475,FUSCCTNBC476,FUSCCTNBC479,FUSCCTNBC480
0,DDX11L1,2,0,1,21,1,0,34,3,5,...,4,0,11,3,4,1,29,2,3,1
1,WASH7P,2099,2041,2297,2526,2642,2272,3124,2055,632,...,2119,2038,1745,1393,2047,1396,2851,2837,1716,2278
2,MIR6859.3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,RP11.34P13.3,1,1,1,5,0,1,0,1,1,...,1,0,1,1,1,0,2,1,0,0
4,MIR1302.9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60478,MT.ND6,320,174,1567,810,458,54,193,188,223,...,184,143,327,238,84,207,256,130,338,448
60479,MT.TE,9,1,8,0,9,2,2,0,1,...,4,1,1,2,3,4,2,6,1,10
60480,MT.CYB,2675,3316,11307,7036,3457,2028,3540,3453,1841,...,7249,4513,18926,6105,4334,3316,8658,2736,10889,6385
60481,MT.TT,173,15,15,12,47,59,32,15,18,...,93,89,77,126,74,28,72,77,167,80
60482,MT.TP,14,8,22,4,31,31,6,12,15,...,24,13,20,11,5,26,16,26,10,55

In [23]:
counts.head(2)

,Symbol,FUSCCTNBC182,FUSCCTNBC203,FUSCCTNBC202,FUSCCTNBC252,FUSCCTNBC187,FUSCCTNBC303,FUSCCTNBC247,FUSCCTNBC285,FUSCCTNBC131,...,FUSCCTNBC473,FUSCCTNBC474,FUSCCTNBC471,FUSCCTNBC472,FUSCCTNBC477,FUSCCTNBC478,FUSCCTNBC475,FUSCCTNBC476,FUSCCTNBC479,FUSCCTNBC480
0,DDX11L1,2,0,1,21,1,0,34,3,5,...,4,0,11,3,4,1,29,2,3,1
1,WASH7P,2099,2041,2297,2526,2642,2272,3124,2055,632,...,2119,2038,1745,1393,2047,1396,2851,2837,1716,2278

In [24]:
gene_names = pd.read_csv('drive/My Drive/Colab Notebooks/GP_lab_data/BRCA1_project/SUM149_BRCA1_DESeq2/ensembl_id_gene_name.csv')
gene_names = gene_names.rename(columns = {'gene_name' : 'Symbol'})
gene_names

               gene_id      Symbol
0      ENSG00000198712      MT-CO2
1      ENSG00000198804      MT-CO1
2      ENSG00000198938      MT-CO3
3      ENSG00000198899     MT-ATP6
4      ENSG00000210082     MT-RNR2
...                ...         ...
58730  ENSG00000276351     RF01973
58731  ENSG00000275661     RF01974
58732  ENSG00000277856  AC233755.2
58733  ENSG00000275063  AC233755.1
58734  ENSG00000268674  AC213203.1

[58735 rows x 2 columns]

In [25]:
common_genes = set(gene_names.Symbol).intersection(set(counts.Symbol))

In [26]:
len(common_genes)

32061

In [27]:
gene_names = gene_names[gene_names['Symbol'].isin(common_genes)]
gene_names = gene_names.drop_duplicates(subset = 'Symbol')
gene_names

               gene_id      Symbol
8      ENSG00000034510      TMSB10
10     ENSG00000156508      EEF1A1
11     ENSG00000227097     RPS28P7
13     ENSG00000184009       ACTG1
15     ENSG00000140988        RPS2
...                ...         ...
58698  ENSG00000228930     MTCO1P3
58700  ENSG00000275167     MIR6815
58701  ENSG00000226115  AP001476.2
58702  ENSG00000233767     PSMA6P3
58717  ENSG00000274847       MAFIP

[32061 rows x 2 columns]

In [28]:
counts = counts[counts['Symbol'].isin(common_genes)]
counts

,Symbol,FUSCCTNBC182,FUSCCTNBC203,FUSCCTNBC202,FUSCCTNBC252,FUSCCTNBC187,FUSCCTNBC303,FUSCCTNBC247,FUSCCTNBC285,FUSCCTNBC131,...,FUSCCTNBC473,FUSCCTNBC474,FUSCCTNBC471,FUSCCTNBC472,FUSCCTNBC477,FUSCCTNBC478,FUSCCTNBC475,FUSCCTNBC476,FUSCCTNBC479,FUSCCTNBC480
0,DDX11L1,2,0,1,21,1,0,34,3,5,...,4,0,11,3,4,1,29,2,3,1
1,WASH7P,2099,2041,2297,2526,2642,2272,3124,2055,632,...,2119,2038,1745,1393,2047,1396,2851,2837,1716,2278
5,FAM138A,0,0,53,4,1,3,1,1,0,...,0,2,3,1,5,0,1,5,0,0
6,OR4G4P,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7,OR4G11P,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60440,TPTE2P4,12,16,4,44,26,18,16,18,14,...,36,75,37,34,37,31,38,12,14,33
60441,CYCSP49,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
60442,SLC25A15P1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,1,6
60443,PARP4P1,3,1,0,0,3,10,3,5,0,...,6,6,2,3,4,4,3,3,2,8
60445,CTBP2P1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [29]:
gene_names = gene_names.set_index('Symbol')
gene_names

                    gene_id
Symbol
TMSB10      ENSG00000034510
EEF1A1      ENSG00000156508
RPS28P7     ENSG00000227097
ACTG1       ENSG00000184009
RPS2        ENSG00000140988
...                     ...
MTCO1P3     ENSG00000228930
MIR6815     ENSG00000275167
AP001476.2  ENSG00000226115
PSMA6P3     ENSG00000233767
MAFIP       ENSG00000274847

[32061 rows x 1 columns]

In [30]:
counts = counts.drop_duplicates()
counts = counts.set_index('Symbol')
counts

,FUSCCTNBC182,FUSCCTNBC203,FUSCCTNBC202,FUSCCTNBC252,FUSCCTNBC187,FUSCCTNBC303,FUSCCTNBC247,FUSCCTNBC285,FUSCCTNBC131,FUSCCTNBC058,...,FUSCCTNBC473,FUSCCTNBC474,FUSCCTNBC471,FUSCCTNBC472,FUSCCTNBC477,FUSCCTNBC478,FUSCCTNBC475,FUSCCTNBC476,FUSCCTNBC479,FUSCCTNBC480
Symbol,,,,,,,,,,,,,,,,,,,,,
DDX11L1,2,0,1,21,1,0,34,3,5,0,...,4,0,11,3,4,1,29,2,3,1
WASH7P,2099,2041,2297,2526,2642,2272,3124,2055,632,897,...,2119,2038,1745,1393,2047,1396,2851,2837,1716,2278
FAM138A,0,0,53,4,1,3,1,1,0,0,...,0,2,3,1,5,0,1,5,0,0
OR4G4P,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
OR4G11P,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TPTE2P4,12,16,4,44,26,18,16,18,14,39,...,36,75,37,34,37,31,38,12,14,33
CYCSP49,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
SLC25A15P1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,1,6
PARP4P1,3,1,0,0,3,10,3,5,0,3,...,6,6,2,3,4,4,3,3,2,8
CTBP2P1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [31]:
counts = pd.concat([gene_names, counts], axis = 'columns')
counts.head(3)

,gene_id,FUSCCTNBC182,FUSCCTNBC203,FUSCCTNBC202,FUSCCTNBC252,FUSCCTNBC187,FUSCCTNBC303,FUSCCTNBC247,FUSCCTNBC285,FUSCCTNBC131,...,FUSCCTNBC473,FUSCCTNBC474,FUSCCTNBC471,FUSCCTNBC472,FUSCCTNBC477,FUSCCTNBC478,FUSCCTNBC475,FUSCCTNBC476,FUSCCTNBC479,FUSCCTNBC480
Symbol,,,,,,,,,,,,,,,,,,,,,
TMSB10,ENSG00000034510,7773,8200,7355,8857,10971,8337,9886,6940,6226,...,8189,7409,17536,6205,4920,4789,6952,10827,5304,7177
EEF1A1,ENSG00000156508,66351,62621,57677,109755,98898,80189,84402,81492,47585,...,64559,89456,55473,48094,103481,52237,88424,30902,55636,53924
RPS28P7,ENSG00000227097,268,220,25,61,209,229,119,372,237,...,302,6,215,136,570,160,69,215,15,139

In [32]:
counts = counts.set_index('gene_id')
counts.head(3)

,FUSCCTNBC182,FUSCCTNBC203,FUSCCTNBC202,FUSCCTNBC252,FUSCCTNBC187,FUSCCTNBC303,FUSCCTNBC247,FUSCCTNBC285,FUSCCTNBC131,FUSCCTNBC058,...,FUSCCTNBC473,FUSCCTNBC474,FUSCCTNBC471,FUSCCTNBC472,FUSCCTNBC477,FUSCCTNBC478,FUSCCTNBC475,FUSCCTNBC476,FUSCCTNBC479,FUSCCTNBC480
gene_id,,,,,,,,,,,,,,,,,,,,,
ENSG00000034510,7773,8200,7355,8857,10971,8337,9886,6940,6226,8999,...,8189,7409,17536,6205,4920,4789,6952,10827,5304,7177
ENSG00000156508,66351,62621,57677,109755,98898,80189,84402,81492,47585,61872,...,64559,89456,55473,48094,103481,52237,88424,30902,55636,53924
ENSG00000227097,268,220,25,61,209,229,119,372,237,91,...,302,6,215,136,570,160,69,215,15,139

#TPM normalization

In [33]:
#TMM normalization with rnanorm
!pip install rnanorm
from rnanorm import TPM

Collecting rnanorm
  Downloading rnanorm-2.2.0-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from rnanorm) (8.3.0)
Requirement already satisfied: numpy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from rnanorm) (2.0.2)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from rnanorm) (2.2.2)
Requirement already satisfied: scikit-learn>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from rnanorm) (1.6.1)
Collecting pandera (from rnanorm)
  Downloading pandera-0.26.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->rnanorm) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->rnanorm) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->rnanorm) (2025.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->rnanorm) (1.16.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->rnanorm) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->rnanorm) (3.6.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from pandera->rnanorm) (25.0)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (from pandera->rnanorm) (2.11.9)
Requirement already satisfied: typeguard in /usr/local/lib/python3.12/dist-packages (from pandera->rnanorm) (4.4.4)
Requirement already satisfied: typing_extensions in /usr/local/lib/python3.12/dist-packages (from pandera->rnanorm) (4.15.0)
Collecting typing_inspect>=0.6.0 (from pandera->rnanorm)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->rnanorm) (1.17.0)
Collecting mypy-extensions>=0.3.0 (from typing_inspect>=0.6.0->pandera->rnanorm)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic->pandera->rnanorm) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic->pandera->rnanorm) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic->pandera->rnanorm) (0.4.2)
Downloading rnanorm-2.2.0-py3-none-any.whl (124 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.6/124.6 kB 6.5 MB/s eta 0:00:00
Downloading pandera-0.26.1-py3-none-any.whl (292 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 292.9/292.9 kB 19.2 MB/s eta 0:00:00
Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Installing collected packages: mypy-extensions, typing_inspect, pandera, rnanorm
Successfully installed mypy-extensions-1.1.0 pandera-0.26.1 rnanorm-2.2.0 typing_inspect-0.9.0

In [34]:
counts = counts.T
counts

gene_id,ENSG00000034510,ENSG00000156508,ENSG00000227097,ENSG00000184009,ENSG00000140988,ENSG00000096384,ENSG00000161016,ENSG00000112306,ENSG00000229117,ENSG00000087086,...,ENSG00000223400,ENSG00000160180,ENSG00000160182,ENSG00000214326,ENSG00000229880,ENSG00000228930,ENSG00000275167,ENSG00000226115,ENSG00000233767,ENSG00000274847
FUSCCTNBC182,7773,66351,268,12556,6558,6816,7228,4545,3136,28406,...,0,4,2,0,0,0,0,1,0,5
FUSCCTNBC203,8200,62621,220,12223,4825,7202,3951,3023,2403,17751,...,0,5,0,0,0,0,0,1,0,1
FUSCCTNBC202,7355,57677,25,10039,16517,15423,7936,2998,5978,11011,...,0,3,7,0,0,0,0,0,0,5
FUSCCTNBC252,8857,109755,61,49848,15173,19943,25320,14667,6967,10771,...,0,0,2,0,0,0,0,3,0,5
FUSCCTNBC187,10971,98898,209,18374,12098,10333,8488,8036,4123,44921,...,0,18,2,0,0,0,0,3,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
FUSCCTNBC478,4789,52237,160,10999,6019,4219,4214,2287,3527,22018,...,0,5,0,0,0,0,0,0,1,10
FUSCCTNBC475,6952,88424,69,32394,10965,12234,6219,4610,4564,12935,...,0,86,20,0,0,0,0,2,0,4
FUSCCTNBC476,10827,30902,215,10599,6167,6625,3499,1461,3149,5649,...,0,327,144,0,0,0,0,0,0,6
FUSCCTNBC479,5304,55636,15,12252,7779,7806,6703,2353,4462,9763,...,0,3030,3117,0,0,0,0,0,0,4
FUSCCTNBC480,7177,53924,139,8183,6228,7829,4955,2543,3852,17382,...,0,317,42,0,0,0,0,2,0,19

In [35]:
norm_counts = TPM(gtf = 'drive/My Drive/Colab Notebooks/Homo_sapiens.GRCh38.113.gtf').fit(counts)
norm_counts = norm_counts.transform(counts)
norm_counts

/usr/local/lib/python3.12/dist-packages/rnanorm/methods/within_sample.py:138: UserWarning: X contains 270 genes that are not in GTF drive/My Drive/Colab Notebooks/Homo_sapiens.GRCh38.113.gtf. This will result in NaN values for missing genes in the output.
  warnings.warn(

array([[2.44715538e+03, 9.56960040e+02, 1.85220607e+02, ...,
        3.53989147e-01, 0.00000000e+00, 4.53832239e-01],
       [3.61527304e+03, 1.26479663e+03, 2.12927405e+02, ...,
        4.95728992e-01, 0.00000000e+00, 1.27109998e-01],
       [3.14259825e+03, 1.12896974e+03, 2.34491890e+01, ...,
        0.00000000e+00, 0.00000000e+00, 6.15926165e-01],
       ...,
       [5.41946605e+03, 7.08611839e+02, 2.36248170e+02, ...,
        0.00000000e+00, 0.00000000e+00, 8.65868768e-01],
       [2.31039914e+03, 1.11022972e+03, 1.43435413e+01, ...,
        0.00000000e+00, 0.00000000e+00, 5.02337906e-01],
       [2.77637422e+03, 9.55631838e+02, 1.18040622e+02, ...,
        8.69925621e-01, 0.00000000e+00, 2.11904959e+00]])

In [36]:
norm_counts = pd.DataFrame(norm_counts)
norm_counts.columns = counts.columns
norm_counts.index = counts.index
norm_counts

gene_id,ENSG00000034510,ENSG00000156508,ENSG00000227097,ENSG00000184009,ENSG00000140988,ENSG00000096384,ENSG00000161016,ENSG00000112306,ENSG00000229117,ENSG00000087086,...,ENSG00000223400,ENSG00000160180,ENSG00000160182,ENSG00000214326,ENSG00000229880,ENSG00000228930,ENSG00000275167,ENSG00000226115,ENSG00000233767,ENSG00000274847
FUSCCTNBC182,2447.155381,956.960040,185.220607,449.733950,398.575769,331.961043,485.891503,1032.302152,410.780763,1997.442072,...,0.0,0.629655,0.589982,0.0,0.0,0.0,0.0,0.353989,0.000000,0.453832
FUSCCTNBC203,3615.273039,1264.796635,212.927405,613.107390,410.668291,491.207544,371.948287,961.535813,440.800609,1747.999510,...,0.0,1.102217,0.000000,0.0,0.0,0.0,0.0,0.495729,0.000000,0.127110
FUSCCTNBC202,3142.598252,1128.969744,23.449189,488.009336,1362.397880,1019.435393,724.029280,924.140245,1062.730790,1050.809965,...,0.0,0.640911,2.802464,0.0,0.0,0.0,0.0,0.000000,0.000000,0.615926
FUSCCTNBC252,3077.853838,1747.266355,46.534260,1970.791018,1017.886626,1072.102967,1878.768767,3677.076850,1007.322009,836.004482,...,0.0,0.000000,0.651219,0.0,0.0,0.0,0.0,1.172194,0.000000,0.500938
FUSCCTNBC187,3355.012056,1385.507343,140.305852,639.268155,714.213497,488.831249,554.244668,1772.914800,524.592853,3068.234283,...,0.0,2.752266,0.573078,0.0,0.0,0.0,0.0,1.031540,0.000000,0.352663
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
FUSCCTNBC478,2089.976932,1044.355445,153.284510,546.111531,507.092984,284.833353,392.680622,720.050386,640.417632,2146.178083,...,0.0,1.091030,0.000000,0.0,0.0,0.0,0.0,0.000000,1.226743,1.258198
FUSCCTNBC475,1880.619141,1095.808585,40.975269,996.981628,572.619756,511.969661,359.219520,899.688318,513.686189,781.535580,...,0.0,11.632138,5.069404,0.0,0.0,0.0,0.0,0.608328,0.000000,0.311963
FUSCCTNBC476,5419.466045,708.611839,236.248170,603.593763,595.921308,513.001821,373.973293,527.592540,655.816273,631.554989,...,0.0,81.840094,67.537764,0.0,0.0,0.0,0.0,0.000000,0.000000,0.865869
FUSCCTNBC479,2310.399136,1110.229721,14.343541,607.186315,654.144769,526.013277,623.449097,739.444346,808.675394,949.856546,...,0.0,659.927355,1272.202144,0.0,0.0,0.0,0.0,0.000000,0.000000,0.502338
FUSCCTNBC480,2776.374225,955.631838,118.040622,360.146416,465.104203,468.517710,409.286104,709.710916,619.986883,1501.848190,...,0.0,61.314660,15.223698,0.0,0.0,0.0,0.0,0.869926,0.000000,2.119050

In [38]:
norm_counts.to_csv('drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/Tissue_res/Fudan_data_processed/fudan_tpm_ensembl_id.csv')

#Select genes in metabolism

In [ ]:
met_genes = pd.read_csv('drive/My Drive/Colab Notebooks/GP_lab_data/FBA_metabolic_atlas_models/human_gem_associated_genes.csv')
met_genes

              gene_id   Symbol
0     ENSG00000198712   MT-CO2
1     ENSG00000198804   MT-CO1
2     ENSG00000198938   MT-CO3
3     ENSG00000198899  MT-ATP6
4     ENSG00000198886   MT-ND4
...               ...      ...
2879  ENSG00000167751     KLK2
2880  ENSG00000129873    CDY2B
2881  ENSG00000182415    CDY2A
2882  ENSG00000172352    CDY1B
2883  ENSG00000172288     CDY1

[2884 rows x 2 columns]

In [ ]:
met_genes_select = met_genes[met_genes['gene_id'].isin(norm_counts.columns)]
met_genes_select = met_genes_select.gene_id.to_list()
len(met_genes_select)

2781

In [ ]:
norm_counts = norm_counts[met_genes_select]
norm_counts

gene_id,ENSG00000156508,ENSG00000167658,ENSG00000111640,ENSG00000167996,ENSG00000074800,ENSG00000084207,ENSG00000196262,ENSG00000111669,ENSG00000176340,ENSG00000005022,...,ENSG00000182601,ENSG00000156885,ENSG00000182156,ENSG00000166948,ENSG00000197838,ENSG00000167751,ENSG00000129873,ENSG00000182415,ENSG00000172352,ENSG00000172288
FUSCCTNBC182,956.960040,539.538971,760.871304,973.002054,262.752109,133.534579,164.251486,157.552703,0.0,119.841830,...,3.203689,0.000000,0.247250,0.0,0.0,0.091410,0.0,0.0,0.0,0.0
FUSCCTNBC203,1264.796635,730.250352,922.593861,1290.995549,255.697698,93.213350,197.403233,206.786923,0.0,184.949952,...,17.591684,0.000000,0.115417,0.0,0.0,0.032003,0.0,0.0,0.0,0.0
FUSCCTNBC202,1128.969744,1848.687173,898.957348,1406.923257,148.447393,60.521240,193.690301,237.535074,0.0,237.254521,...,5.720976,0.000000,0.279633,0.0,0.0,1.643769,0.0,0.0,0.0,0.0
FUSCCTNBC252,1747.266355,581.078268,3372.555824,1851.332215,818.721060,489.318098,436.202149,513.529717,0.0,378.710531,...,2.698692,0.000000,0.136456,0.0,0.0,0.025224,0.0,0.0,0.0,0.0
FUSCCTNBC187,1385.507343,742.014642,1427.305612,1060.494448,278.954255,252.544141,163.392127,239.974476,0.0,144.150292,...,20.841528,0.000000,0.040028,0.0,0.0,0.022198,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
FUSCCTNBC478,1044.355445,561.879600,598.939549,1056.527251,140.398149,165.031760,105.400057,109.609069,0.0,98.846329,...,147.135098,0.000000,0.456981,0.0,0.0,0.031678,0.0,0.0,0.0,0.0
FUSCCTNBC475,1095.808585,592.801812,2044.711115,1037.609870,447.712738,164.296971,116.761385,292.092302,0.0,127.915245,...,7.823638,0.000000,0.247857,0.0,0.0,0.019636,0.0,0.0,0.0,0.0
FUSCCTNBC476,708.611839,649.623373,668.473998,749.374853,90.691287,153.181953,160.608887,91.190573,0.0,116.489975,...,3.217018,0.487852,0.065518,0.0,0.0,0.072667,0.0,0.0,0.0,0.0
FUSCCTNBC479,1110.229721,796.496384,628.745181,874.583831,152.378127,91.411616,108.905135,124.427564,0.0,101.631600,...,23.096309,0.000000,0.228063,0.0,0.0,0.126474,0.0,0.0,0.0,0.0
FUSCCTNBC480,955.631838,592.039445,587.179825,878.058384,107.424807,132.942290,95.690535,112.879293,0.0,102.184093,...,7.769449,0.000000,1.367132,0.0,0.0,0.056160,0.0,0.0,0.0,0.0

In [ ]:
norm_counts = norm_counts.T
norm_counts = pd.concat([met_genes.set_index('gene_id'), norm_counts], axis = 'columns')
norm_counts = norm_counts.set_index('Symbol')
norm_counts.index.name = None
norm_counts = norm_counts.T
norm_counts

,MT-CO2,MT-CO1,MT-CO3,MT-ATP6,MT-ND4,MT-ND4L,MT-ND2,MT-ND3,EEF1A1,MT-ND1,...,HS3ST4,COX6A2,ENPP7,TGM6,CYP2A13,KLK2,CDY2B,CDY2A,CDY1B,CDY1
FUSCCTNBC182,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,956.960040,NaN,...,3.203689,0.000000,0.247250,0.0,0.0,0.091410,0.0,0.0,0.0,0.0
FUSCCTNBC203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1264.796635,NaN,...,17.591684,0.000000,0.115417,0.0,0.0,0.032003,0.0,0.0,0.0,0.0
FUSCCTNBC202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1128.969744,NaN,...,5.720976,0.000000,0.279633,0.0,0.0,1.643769,0.0,0.0,0.0,0.0
FUSCCTNBC252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1747.266355,NaN,...,2.698692,0.000000,0.136456,0.0,0.0,0.025224,0.0,0.0,0.0,0.0
FUSCCTNBC187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1385.507343,NaN,...,20.841528,0.000000,0.040028,0.0,0.0,0.022198,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
FUSCCTNBC478,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1044.355445,NaN,...,147.135098,0.000000,0.456981,0.0,0.0,0.031678,0.0,0.0,0.0,0.0
FUSCCTNBC475,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1095.808585,NaN,...,7.823638,0.000000,0.247857,0.0,0.0,0.019636,0.0,0.0,0.0,0.0
FUSCCTNBC476,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,708.611839,NaN,...,3.217018,0.487852,0.065518,0.0,0.0,0.072667,0.0,0.0,0.0,0.0
FUSCCTNBC479,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1110.229721,NaN,...,23.096309,0.000000,0.228063,0.0,0.0,0.126474,0.0,0.0,0.0,0.0
FUSCCTNBC480,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,955.631838,NaN,...,7.769449,0.000000,1.367132,0.0,0.0,0.056160,0.0,0.0,0.0,0.0

In [ ]:
import joblib

model = joblib.load('drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/Tissue_res/ElasticNet.pkl')

In [ ]:
model_features = model.feature_names_in_
model_features

array(['NAT1', 'NAT2', 'SERPINA3', ..., 'PGAM2', 'CEMP1', 'CDY2A'],
      dtype=object)

In [ ]:
filtered_data = norm_counts[model_features]

In [ ]:
filtered_data.to_csv('drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/Tissue_res/Fudan_data_processed/fudan_tpm_met_genes_y_features.csv')