#Import modules

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np

#Data

In [3]:
data = pd.read_csv('drive/My Drive/Colab Notebooks/Deep_learning_metabolomics_prediction/BulkRNABert_data/benedetti_processed_for_bulkrnabert.csv', index_col = 0)
data = data.fillna(0)
data = data.T
data

,ENSG00000000003,ENSG00000000005,ENSG00000000419,ENSG00000000457,ENSG00000000460,ENSG00000000938,ENSG00000000971,ENSG00000001036,ENSG00000001084,ENSG00000001167,...,ENSG00000284519,ENSG00000284532,ENSG00000284535,ENSG00000284543,ENSG00000284557,ENSG00000284564,ENSG00000284574,ENSG00000284587,ENSG00000284595,ENSG00000284596
MSKC-00397,87.492331,0.083832,119.085084,10.729475,0.0,33.977064,122.411217,73.264745,19.850590,11.119178,...,0.0,0.0,0.0,0.123602,0.0,306.711498,0.0,0.0,0.0,5.377687
MSKC-00399,126.939144,0.991959,102.072551,13.968331,0.0,6.967811,25.971543,53.316864,18.405792,10.666253,...,0.0,0.0,0.0,0.228523,0.0,210.691766,0.0,0.0,0.0,0.000000
MSKC-00400,46.151968,0.642128,121.438296,11.219856,0.0,18.313074,8.719379,44.436246,30.628803,10.574773,...,0.0,0.0,0.0,0.000000,0.0,347.973049,0.0,0.0,0.0,15.446746
MSKC-00404,43.768328,0.078898,100.218984,10.260763,0.0,42.268495,211.808477,58.642671,29.612030,8.383824,...,0.0,0.0,0.0,0.000000,0.0,421.511982,0.0,0.0,0.0,15.183403
MSKC-00405,101.558497,0.482484,101.428590,10.976298,0.0,42.084138,109.829882,60.758221,33.767010,13.110726,...,0.0,0.0,0.0,0.076219,0.0,371.932961,0.0,0.0,0.0,13.264478
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
PT-P44H,2.926636,0.024386,3.544263,1.864470,0.0,0.986396,0.609692,3.835325,2.107799,5.718623,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000
PT-R55F,2.765044,0.117687,2.837619,1.752504,0.0,0.718822,0.721507,2.362707,1.525446,6.444395,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000
PT-RN5K,2.467863,0.095518,1.654335,1.146944,0.0,1.593019,1.877323,2.668766,0.959484,6.523860,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000
PT-UTHO,2.299435,0.037768,3.951971,2.310034,0.0,1.104326,0.913463,4.308637,2.769931,10.115746,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000
PT-WVLH,2.727859,0.039638,3.931738,1.522523,0.0,0.497946,0.758622,2.597496,1.920852,4.426076,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000

In [ ]:
#For some reason this sample produced error and could not be processed

data = data.drop(labels = ['MSKC-00411'], axis = 'index')
data

,ENSG00000000003,ENSG00000000005,ENSG00000000419,ENSG00000000457,ENSG00000000460,ENSG00000000938,ENSG00000000971,ENSG00000001036,ENSG00000001084,ENSG00000001167,...,ENSG00000284519,ENSG00000284532,ENSG00000284535,ENSG00000284543,ENSG00000284557,ENSG00000284564,ENSG00000284574,ENSG00000284587,ENSG00000284595,ENSG00000284596
MSKC-00397,87.492331,0.083832,119.085084,10.729475,0.0,33.977064,122.411217,73.264745,19.850590,11.119178,...,0.0,0.0,0.0,0.123602,0.0,306.711498,0.0,0.0,0.0,5.377687
MSKC-00399,126.939144,0.991959,102.072551,13.968331,0.0,6.967811,25.971543,53.316864,18.405792,10.666253,...,0.0,0.0,0.0,0.228523,0.0,210.691766,0.0,0.0,0.0,0.000000
MSKC-00400,46.151968,0.642128,121.438296,11.219856,0.0,18.313074,8.719379,44.436246,30.628803,10.574773,...,0.0,0.0,0.0,0.000000,0.0,347.973049,0.0,0.0,0.0,15.446746
MSKC-00404,43.768328,0.078898,100.218984,10.260763,0.0,42.268495,211.808477,58.642671,29.612030,8.383824,...,0.0,0.0,0.0,0.000000,0.0,421.511982,0.0,0.0,0.0,15.183403
MSKC-00405,101.558497,0.482484,101.428590,10.976298,0.0,42.084138,109.829882,60.758221,33.767010,13.110726,...,0.0,0.0,0.0,0.076219,0.0,371.932961,0.0,0.0,0.0,13.264478
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
PT-P44H,2.926636,0.024386,3.544263,1.864470,0.0,0.986396,0.609692,3.835325,2.107799,5.718623,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000
PT-R55F,2.765044,0.117687,2.837619,1.752504,0.0,0.718822,0.721507,2.362707,1.525446,6.444395,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000
PT-RN5K,2.467863,0.095518,1.654335,1.146944,0.0,1.593019,1.877323,2.668766,0.959484,6.523860,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000
PT-UTHO,2.299435,0.037768,3.951971,2.310034,0.0,1.104326,0.913463,4.308637,2.769931,10.115746,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000
PT-WVLH,2.727859,0.039638,3.931738,1.522523,0.0,0.497946,0.758622,2.597496,1.920852,4.426076,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000

In [ ]:
#Assert that genes are in the correct order

with open("drive/My Drive/Colab Notebooks/Deep_learning_metabolomics_prediction/BulkRNABert_data/common_gene_id.txt") as f:
    gene_list = [line.strip() for line in f]

print(len(gene_list))


data = data.reindex(columns = gene_list)
data.head(3)

19062

,ENSG00000000003,ENSG00000000005,ENSG00000000419,ENSG00000000457,ENSG00000000460,ENSG00000000938,ENSG00000000971,ENSG00000001036,ENSG00000001084,ENSG00000001167,...,ENSG00000284519,ENSG00000284532,ENSG00000284535,ENSG00000284543,ENSG00000284557,ENSG00000284564,ENSG00000284574,ENSG00000284587,ENSG00000284595,ENSG00000284596
MSKC-00397,87.492331,0.083832,119.085084,10.729475,0.0,33.977064,122.411217,73.264745,19.850590,11.119178,...,0.0,0.0,0.0,0.123602,0.0,306.711498,0.0,0.0,0.0,5.377687
MSKC-00399,126.939144,0.991959,102.072551,13.968331,0.0,6.967811,25.971543,53.316864,18.405792,10.666253,...,0.0,0.0,0.0,0.228523,0.0,210.691766,0.0,0.0,0.0,0.000000
MSKC-00400,46.151968,0.642128,121.438296,11.219856,0.0,18.313074,8.719379,44.436246,30.628803,10.574773,...,0.0,0.0,0.0,0.000000,0.0,347.973049,0.0,0.0,0.0,15.446746

#BulkRNABert

In [ ]:
!pip install --upgrade git+https://github.com/huggingface/transformers.git --quiet
!pip install torch --quiet

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done

In [ ]:
from huggingface_hub import hf_hub_download
import numpy as np
import pandas as pd
from transformers import AutoConfig, AutoModel, AutoTokenizer
import torch

In [ ]:
config = AutoConfig.from_pretrained(
    "InstaDeepAI/BulkRNABert",
    trust_remote_code=True,
)

config.embeddings_layers_to_save = (4,)

tokenizer = AutoTokenizer.from_pretrained("InstaDeepAI/BulkRNABert", trust_remote_code=True)
model = AutoModel.from_pretrained(
    "InstaDeepAI/BulkRNABert",
    config=config,
    trust_remote_code=True,
)

# Determine the device to use
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device) # Move the model to the selected device


gene_expression_array = data.to_numpy()
gene_expression_array = np.log10(1 + gene_expression_array)
# assert gene_expression_array.shape[1] == config.n_genes # This assertion might fail with your data, keep it commented for now


arrays = []
for i in range(gene_expression_array.shape[0]):
  #Tokenize
  # Process each row as a single sample
  gene_expression_ids = tokenizer.batch_encode_plus(gene_expression_array[i:i+1, :], return_tensors="pt")["input_ids"]

  # Move the input tensor to the same device as the model
  gene_expression_ids = gene_expression_ids.to(device)

  # Compute BulkRNABert's embeddings
  gene_expression_mean_embeddings = model(gene_expression_ids)["embeddings_4"].mean(axis=1)
  gene_expression_mean_embeddings = gene_expression_mean_embeddings.detach().cpu().numpy()
  arrays.append(gene_expression_mean_embeddings)
  print(f'Sample {i+1} done!')


res = np.concatenate(arrays, axis=0)
res.shape

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
The module name InstaDeepAI/BulkRNABert (originally InstaDeepAI/BulkRNABert) is not a valid Python identifier. Please rename the original module to avoid import issues.
The module name InstaDeepAI/BulkRNABert (originally InstaDeepAI/BulkRNABert) is not a valid Python identifier. Please rename the original module to avoid import issues.
The module name InstaDeepAI/BulkRNABert (originally InstaDeepAI/BulkRNABert) is not a valid Python identifier. Please rename the original module to avoid import issues.

Sample 1 done!
Sample 2 done!
Sample 3 done!
Sample 4 done!
Sample 5 done!
Sample 6 done!
Sample 7 done!
Sample 8 done!
Sample 9 done!
Sample 10 done!
Sample 11 done!
Sample 12 done!
Sample 13 done!
Sample 14 done!
Sample 15 done!
Sample 16 done!
Sample 17 done!
Sample 18 done!
Sample 19 done!
Sample 20 done!
Sample 21 done!
Sample 22 done!
Sample 23 done!
Sample 24 done!
Sample 25 done!
Sample 26 done!
Sample 27 done!
Sample 28 done!
Sample 29 done!
Sample 30 done!
Sample 31 done!
Sample 32 done!
Sample 33 done!
Sample 34 done!
Sample 35 done!
Sample 36 done!
Sample 37 done!
Sample 38 done!
Sample 39 done!
Sample 40 done!
Sample 41 done!
Sample 42 done!
Sample 43 done!
Sample 44 done!
Sample 45 done!
Sample 46 done!
Sample 47 done!
Sample 48 done!
Sample 49 done!
Sample 50 done!
Sample 51 done!
Sample 52 done!
Sample 53 done!
Sample 54 done!
Sample 55 done!
Sample 56 done!
Sample 57 done!
Sample 58 done!
Sample 59 done!
Sample 60 done!
Sample 61 done!
Sample 62 done!
Sample 63 done!
Sample 64 done!
Sample 65 done!
Sample 66 done!
Sample 67 done!
Sample 68 done!
Sample 69 done!
Sample 70 done!
Sample 71 done!
Sample 72 done!
Sample 73 done!
Sample 74 done!
Sample 75 done!
Sample 76 done!
Sample 77 done!
Sample 78 done!
Sample 79 done!
Sample 80 done!
Sample 81 done!
Sample 82 done!
Sample 83 done!
Sample 84 done!
Sample 85 done!
Sample 86 done!
Sample 87 done!
Sample 88 done!
Sample 89 done!
Sample 90 done!
Sample 91 done!
Sample 92 done!
Sample 93 done!
Sample 94 done!
Sample 95 done!
Sample 96 done!
Sample 97 done!
Sample 98 done!
Sample 99 done!
Sample 100 done!
Sample 101 done!
Sample 102 done!
Sample 103 done!
Sample 104 done!
Sample 105 done!
Sample 106 done!
Sample 107 done!
Sample 108 done!
Sample 109 done!
Sample 110 done!
Sample 111 done!
Sample 112 done!
Sample 113 done!
Sample 114 done!
Sample 115 done!
Sample 116 done!
Sample 117 done!
Sample 118 done!
Sample 119 done!
Sample 120 done!
Sample 121 done!
Sample 122 done!
Sample 123 done!
Sample 124 done!
Sample 125 done!
Sample 126 done!
Sample 127 done!
Sample 128 done!
Sample 129 done!
Sample 130 done!
Sample 131 done!
Sample 132 done!
Sample 133 done!
Sample 134 done!
Sample 135 done!
Sample 136 done!
Sample 137 done!
Sample 138 done!
Sample 139 done!
Sample 140 done!
Sample 141 done!
Sample 142 done!
Sample 143 done!
Sample 144 done!
Sample 145 done!
Sample 146 done!
Sample 147 done!
Sample 148 done!
Sample 149 done!
Sample 150 done!
Sample 151 done!
Sample 152 done!
Sample 153 done!
Sample 154 done!
Sample 155 done!
Sample 156 done!
Sample 157 done!
Sample 158 done!
Sample 159 done!
Sample 160 done!
Sample 161 done!
Sample 162 done!
Sample 163 done!
Sample 164 done!
Sample 165 done!
Sample 166 done!
Sample 167 done!
Sample 168 done!
Sample 169 done!
Sample 170 done!
Sample 171 done!
Sample 172 done!
Sample 173 done!
Sample 174 done!
Sample 175 done!
Sample 176 done!
Sample 177 done!
Sample 178 done!
Sample 179 done!
Sample 180 done!
Sample 181 done!
Sample 182 done!
Sample 183 done!
Sample 184 done!
Sample 185 done!
Sample 186 done!
Sample 187 done!
Sample 188 done!
Sample 189 done!
Sample 190 done!
Sample 191 done!
Sample 192 done!
Sample 193 done!
Sample 194 done!
Sample 195 done!
Sample 196 done!
Sample 197 done!
Sample 198 done!
Sample 199 done!
Sample 200 done!
Sample 201 done!
Sample 202 done!
Sample 203 done!
Sample 204 done!
Sample 205 done!
Sample 206 done!
Sample 207 done!
Sample 208 done!
Sample 209 done!
Sample 210 done!
Sample 211 done!
Sample 212 done!
Sample 213 done!
Sample 214 done!
Sample 215 done!
Sample 216 done!
Sample 217 done!
Sample 218 done!
Sample 219 done!
Sample 220 done!
Sample 221 done!
Sample 222 done!
Sample 223 done!
Sample 224 done!
Sample 225 done!
Sample 226 done!
Sample 227 done!
Sample 228 done!
Sample 229 done!
Sample 230 done!
Sample 231 done!
Sample 232 done!
Sample 233 done!
Sample 234 done!
Sample 235 done!
Sample 236 done!
Sample 237 done!
Sample 238 done!
Sample 239 done!
Sample 240 done!
Sample 241 done!
Sample 242 done!
Sample 243 done!
Sample 244 done!
Sample 245 done!
Sample 246 done!
Sample 247 done!
Sample 248 done!
Sample 249 done!
Sample 250 done!
Sample 251 done!
Sample 252 done!
Sample 253 done!
Sample 254 done!
Sample 255 done!
Sample 256 done!
Sample 257 done!
Sample 258 done!
Sample 259 done!
Sample 260 done!
Sample 261 done!
Sample 262 done!
Sample 263 done!
Sample 264 done!
Sample 265 done!
Sample 266 done!
Sample 267 done!
Sample 268 done!
Sample 269 done!
Sample 270 done!
Sample 271 done!
Sample 272 done!
Sample 273 done!
Sample 274 done!
Sample 275 done!
Sample 276 done!
Sample 277 done!
Sample 278 done!
Sample 279 done!
Sample 280 done!
Sample 281 done!
Sample 282 done!
Sample 283 done!
Sample 284 done!
Sample 285 done!
Sample 286 done!
Sample 287 done!
Sample 288 done!
Sample 289 done!
Sample 290 done!
Sample 291 done!
Sample 292 done!
Sample 293 done!
Sample 294 done!
Sample 295 done!
Sample 296 done!
Sample 297 done!
Sample 298 done!
Sample 299 done!
Sample 300 done!
Sample 301 done!
Sample 302 done!
Sample 303 done!
Sample 304 done!
Sample 305 done!
Sample 306 done!
Sample 307 done!
Sample 308 done!
Sample 309 done!
Sample 310 done!
Sample 311 done!
Sample 312 done!
Sample 313 done!
Sample 314 done!
Sample 315 done!
Sample 316 done!
Sample 317 done!
Sample 318 done!
Sample 319 done!
Sample 320 done!
Sample 321 done!
Sample 322 done!
Sample 323 done!
Sample 324 done!
Sample 325 done!
Sample 326 done!
Sample 327 done!
Sample 328 done!
Sample 329 done!
Sample 330 done!
Sample 331 done!
Sample 332 done!
Sample 333 done!
Sample 334 done!
Sample 335 done!
Sample 336 done!
Sample 337 done!
Sample 338 done!
Sample 339 done!
Sample 340 done!
Sample 341 done!
Sample 342 done!
Sample 343 done!
Sample 344 done!
Sample 345 done!
Sample 346 done!
Sample 347 done!
Sample 348 done!
Sample 349 done!
Sample 350 done!
Sample 351 done!
Sample 352 done!
Sample 353 done!
Sample 354 done!
Sample 355 done!
Sample 356 done!
Sample 357 done!
Sample 358 done!
Sample 359 done!
Sample 360 done!
Sample 361 done!
Sample 362 done!
Sample 363 done!
Sample 364 done!
Sample 365 done!
Sample 366 done!
Sample 367 done!
Sample 368 done!
Sample 369 done!
Sample 370 done!
Sample 371 done!
Sample 372 done!
Sample 373 done!
Sample 374 done!
Sample 375 done!
Sample 376 done!
Sample 377 done!
Sample 378 done!
Sample 379 done!
Sample 380 done!
Sample 381 done!
Sample 382 done!
Sample 383 done!
Sample 384 done!
Sample 385 done!
Sample 386 done!
Sample 387 done!
Sample 388 done!
Sample 389 done!
Sample 390 done!
Sample 391 done!
Sample 392 done!
Sample 393 done!
Sample 394 done!
Sample 395 done!
Sample 396 done!
Sample 397 done!
Sample 398 done!
Sample 399 done!
Sample 400 done!
Sample 401 done!
Sample 402 done!
Sample 403 done!
Sample 404 done!
Sample 405 done!
Sample 406 done!
Sample 407 done!
Sample 408 done!
Sample 409 done!
Sample 410 done!
Sample 411 done!
Sample 412 done!
Sample 413 done!
Sample 414 done!
Sample 415 done!
Sample 416 done!
Sample 417 done!
Sample 418 done!
Sample 419 done!
Sample 420 done!
Sample 421 done!
Sample 422 done!
Sample 423 done!
Sample 424 done!
Sample 425 done!
Sample 426 done!
Sample 427 done!
Sample 428 done!
Sample 429 done!
Sample 430 done!
Sample 431 done!
Sample 432 done!
Sample 433 done!
Sample 434 done!
Sample 435 done!
Sample 436 done!
Sample 437 done!
Sample 438 done!
Sample 439 done!
Sample 440 done!
Sample 441 done!
Sample 442 done!

(442, 256)

In [ ]:
res_df = pd.DataFrame(res, index = data.index)
res_df

,0,1,2,3,4,5,6,7,8,9,...,246,247,248,249,250,251,252,253,254,255
MSKC-00397,0.913342,0.621870,0.922743,-1.037893,0.301553,0.715152,0.206450,0.652923,0.059982,0.294590,...,0.175746,-0.133243,0.109954,0.040338,0.067777,1.130643,0.370476,0.344561,-0.118917,0.710770
MSKC-00399,0.818992,0.296598,0.773417,-0.866102,0.307585,0.849735,0.420930,0.668587,-0.094435,-0.175127,...,0.098970,-0.331284,0.045357,-0.092454,-0.062354,1.144853,0.325433,0.280668,-0.220902,0.927439
MSKC-00400,1.022583,0.321305,1.228209,-1.065100,0.499109,0.576022,0.248522,0.579413,-0.226993,0.099416,...,-0.146370,-0.176852,-0.045236,-0.197819,-0.038868,1.062385,0.275921,0.211972,-0.131308,0.676849
MSKC-00404,1.022246,0.744968,1.156375,-1.013309,0.230046,0.506557,0.223892,0.750233,0.054625,0.459118,...,0.257191,-0.178159,0.146739,-0.014896,0.050930,1.156376,0.497806,0.327070,-0.180218,0.540008
MSKC-00405,0.971925,0.678423,0.743625,-1.148056,0.332629,0.655422,0.190903,0.555662,0.075683,0.220108,...,0.057747,-0.262169,-0.035882,-0.028639,0.074571,1.213970,0.348896,0.325905,-0.168206,0.697458
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
PT-P44H,0.533675,-0.316429,3.371897,-0.029202,1.088933,0.488736,-0.090113,0.487655,-0.186383,0.200859,...,0.820505,-0.337173,0.678901,-0.616893,-0.337793,0.528891,0.194825,-0.301103,0.193381,0.732298
PT-R55F,0.582715,-0.349183,3.070900,-0.071421,0.945457,0.581417,0.043929,0.615177,-0.309759,0.207503,...,0.907579,-0.257814,0.802587,-0.588829,-0.070505,0.612147,0.205887,-0.325677,0.269320,0.858617
PT-RN5K,0.562467,-0.276826,3.437461,-0.140747,1.013584,0.594322,-0.079603,0.749423,-0.308488,0.279132,...,0.957076,-0.202017,0.776208,-0.609761,-0.075496,0.633105,0.102027,-0.451013,0.353921,0.800787
PT-UTHO,0.593032,-0.350178,2.716498,-0.164287,0.824521,0.557042,0.101592,0.653268,-0.325775,0.185995,...,0.867591,-0.184794,0.821017,-0.624438,-0.057503,0.671240,0.301893,-0.214687,0.284997,0.922281
PT-WVLH,0.582424,-0.264964,3.321706,0.034658,1.136991,0.432576,-0.175361,0.330305,-0.181148,0.127783,...,0.765622,-0.378464,0.569642,-0.602240,-0.469671,0.464096,0.159397,-0.271853,0.121934,0.777083

In [ ]:
res_df.to_csv('drive/My Drive/Colab Notebooks/Deep_learning_metabolomics_prediction/BulkRNABert_data/bulkrnabert_embeddings.csv', index = True)

In [ ]:
# ############# Original Code ##############

# config = AutoConfig.from_pretrained(
#     "InstaDeepAI/BulkRNABert",
#     trust_remote_code=True,
# )

# config.embeddings_layers_to_save = (4,)

# tokenizer = AutoTokenizer.from_pretrained("InstaDeepAI/BulkRNABert", trust_remote_code=True)
# model = AutoModel.from_pretrained(
#     "InstaDeepAI/BulkRNABert",
#     config=config,
#     trust_remote_code=True,
# )

# # Load bulk RNA-seq data and preprocess them.
# csv_path = hf_hub_download(
#     repo_id="InstaDeepAI/BulkRNABert",
#     filename="data/tcga_sample.csv",
#     repo_type="model",
# )
# gene_expression_array = pd.read_csv(csv_path).drop(["identifier"], axis=1).to_numpy()[:1, :]
# gene_expression_array = np.log10(1 + gene_expression_array)
# assert gene_expression_array.shape[1] == config.n_genes

# # Tokenize
# gene_expression_ids = tokenizer.batch_encode_plus(gene_expression_array, return_tensors="pt")["input_ids"]

# # Compute BulkRNABert's embeddings
# gene_expression_mean_embeddings = model(gene_expression_ids)["embeddings_4"].mean(axis=1)  # embeddings can be used for downstream tasks.