#Import modules

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

#Data

In [3]:
rna = pd.read_csv('drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/CCLE_OmicsExpressionProteinCodingGenesTPMLogp1BatchCorrected.csv', index_col = 0)
rna

,TFE3 (7030),MMADHC (27249),PABPC1L (80336),RELL2 (285613),GPT (2875),GUSB (2990),H4-16 (121504),DDB2 (1643),RPS4X (6191),HINFP (25988),...,OR2A42 (402317),HOXB7 (3217),NSA2 (10412),UGT2B11 (10720),ZNF747 (65988),NAA60 (79903),MYH4 (4622),MTAP (4507),C14orf93 (60686),NR3C2 (4306)
ACH-000873,3.607691,3.531071,4.982285,2.326016,0.607679,5.118549,1.282028,4.512297,10.075438,2.954654,...,0.042564,3.870581,5.178480,-0.007723,2.005498,4.213717,-0.001724,3.904800,2.190931,0.203910
ACH-000860,4.192566,6.865682,4.853288,2.725583,0.197016,5.666426,1.154470,4.306808,10.215240,4.096901,...,0.031621,-0.005897,6.749713,-0.007723,1.393644,4.334535,-0.001724,4.812949,3.366939,0.370726
ACH-000439,3.265517,5.804615,1.777636,4.185835,0.389025,6.593342,0.410244,4.411381,11.644890,4.744030,...,-0.013226,-0.033868,6.877322,1.596383,3.143557,4.624226,-0.001724,4.122929,2.197136,0.015412
ACH-000318,3.705500,5.813170,4.536005,2.290409,0.471169,5.160089,2.325673,5.017968,9.163992,2.578735,...,-0.013226,3.051092,5.610027,-0.007723,2.334419,3.881219,-0.001724,0.394778,3.217293,0.277760
ACH-001142,6.105227,7.051513,4.457555,2.543055,0.022363,4.589966,2.369987,4.105131,10.179188,3.795200,...,0.053402,3.582671,7.416571,-0.007723,2.294077,4.889203,-0.001724,4.379944,2.355443,0.520338
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ACH-001843,5.343844,6.553367,5.674036,3.390159,0.644076,5.555928,1.037326,4.275462,11.191982,3.898700,...,0.026960,5.222260,7.411799,0.010848,0.563822,4.885868,0.000741,4.898450,2.716015,0.067286
ACH-002074,5.252185,6.258400,2.872415,1.886574,0.796319,6.534374,3.269016,4.587816,9.946776,4.086724,...,0.104563,4.270369,6.188434,0.010848,3.447185,5.964889,0.000741,4.181277,3.931034,0.695929
ACH-001164,4.050893,6.248805,2.790849,1.599247,0.663686,5.533158,0.646986,5.091849,10.865960,3.390254,...,0.026960,0.470043,6.898124,1.385374,2.641063,4.824132,0.022977,3.384695,2.413815,0.221968
ACH-003180,5.161680,7.678250,1.932748,1.463134,0.394206,6.464239,0.360318,4.761168,9.531740,3.015668,...,0.104563,4.741295,6.250017,0.010848,2.652496,5.139537,0.044994,4.773658,2.686730,0.011768
ACH-001979,4.986577,7.612689,3.058782,3.065330,0.394206,6.845823,0.739760,5.612840,11.378735,2.739342,...,0.026960,4.768690,7.245916,0.010848,2.319096,5.181626,0.000741,4.881492,2.779229,0.528664

In [4]:
rna = rna.rename(columns=lambda x: x.split(' (')[0] if ' (' in x else x)

In [5]:
rna = rna.loc[rna.index.notnull()]
rna

,TFE3,MMADHC,PABPC1L,RELL2,GPT,GUSB,H4-16,DDB2,RPS4X,HINFP,...,OR2A42,HOXB7,NSA2,UGT2B11,ZNF747,NAA60,MYH4,MTAP,C14orf93,NR3C2
ACH-000873,3.607691,3.531071,4.982285,2.326016,0.607679,5.118549,1.282028,4.512297,10.075438,2.954654,...,0.042564,3.870581,5.178480,-0.007723,2.005498,4.213717,-0.001724,3.904800,2.190931,0.203910
ACH-000860,4.192566,6.865682,4.853288,2.725583,0.197016,5.666426,1.154470,4.306808,10.215240,4.096901,...,0.031621,-0.005897,6.749713,-0.007723,1.393644,4.334535,-0.001724,4.812949,3.366939,0.370726
ACH-000439,3.265517,5.804615,1.777636,4.185835,0.389025,6.593342,0.410244,4.411381,11.644890,4.744030,...,-0.013226,-0.033868,6.877322,1.596383,3.143557,4.624226,-0.001724,4.122929,2.197136,0.015412
ACH-000318,3.705500,5.813170,4.536005,2.290409,0.471169,5.160089,2.325673,5.017968,9.163992,2.578735,...,-0.013226,3.051092,5.610027,-0.007723,2.334419,3.881219,-0.001724,0.394778,3.217293,0.277760
ACH-001142,6.105227,7.051513,4.457555,2.543055,0.022363,4.589966,2.369987,4.105131,10.179188,3.795200,...,0.053402,3.582671,7.416571,-0.007723,2.294077,4.889203,-0.001724,4.379944,2.355443,0.520338
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ACH-001843,5.343844,6.553367,5.674036,3.390159,0.644076,5.555928,1.037326,4.275462,11.191982,3.898700,...,0.026960,5.222260,7.411799,0.010848,0.563822,4.885868,0.000741,4.898450,2.716015,0.067286
ACH-002074,5.252185,6.258400,2.872415,1.886574,0.796319,6.534374,3.269016,4.587816,9.946776,4.086724,...,0.104563,4.270369,6.188434,0.010848,3.447185,5.964889,0.000741,4.181277,3.931034,0.695929
ACH-001164,4.050893,6.248805,2.790849,1.599247,0.663686,5.533158,0.646986,5.091849,10.865960,3.390254,...,0.026960,0.470043,6.898124,1.385374,2.641063,4.824132,0.022977,3.384695,2.413815,0.221968
ACH-003180,5.161680,7.678250,1.932748,1.463134,0.394206,6.464239,0.360318,4.761168,9.531740,3.015668,...,0.104563,4.741295,6.250017,0.010848,2.652496,5.139537,0.044994,4.773658,2.686730,0.011768
ACH-001979,4.986577,7.612689,3.058782,3.065330,0.394206,6.845823,0.739760,5.612840,11.378735,2.739342,...,0.026960,4.768690,7.245916,0.010848,2.319096,5.181626,0.000741,4.881492,2.779229,0.528664

In [6]:
cell_line_anotations = pd.read_csv('drive/My Drive/Colab Notebooks/GP_lab_data/BRCA1_project/CCLE/Cell_lines_annotations_20181226.txt', sep = '\t', usecols = ['CCLE_ID',	'depMapID',	'Name',	'Site_Primary'])
cell_line_anotations

,CCLE_ID,depMapID,Name,Site_Primary
0,DMS53_LUNG,ACH-000698,DMS 53,lung
1,SW1116_LARGE_INTESTINE,ACH-000489,SW1116,large_intestine
2,NCIH1694_LUNG,ACH-000431,NCI-H1694,lung
3,P3HR1_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE,ACH-000707,P3HR-1,haematopoietic_and_lymphoid_tissue
4,HUT78_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE,ACH-000509,HuT 78,haematopoietic_and_lymphoid_tissue
...,...,...,...,...
1456,GEO_LARGE_INTESTINE,ACH-002394,NaN,NaN
1457,NCIH2330_LUNG,NaN,NaN,NaN
1458,LP6_SOFT_TISSUE,ACH-001116,NaN,NaN
1459,HS578BST_BREAST,NaN,NaN,NaN
1460,LC1SQ_LUNG,ACH-002156,NaN,NaN

In [7]:
metabolites = pd.read_csv('drive/My Drive/Colab Notebooks/GP_lab_data/BRCA1_project/CCLE/CCLE_metabolomics_20190502.csv')
metabolites

,CCLE_ID,DepMap_ID,2-aminoadipate,3-phosphoglycerate,alpha-glycerophosphate,4-pyridoxate,aconitate,adenine,adipate,alpha-ketoglutarate,...,C56:8 TAG,C56:7 TAG,C56:6 TAG,C56:5 TAG,C56:4 TAG,C56:3 TAG,C56:2 TAG,C58:8 TAG,C58:7 TAG,C58:6 TAG
0,DMS53_LUNG,ACH-000698,6.112727,6.034198,5.896896,6.000532,5.513618,5.868529,5.977177,5.693074,...,6.070239,6.133433,6.091089,6.257711,6.372732,6.202511,5.939576,6.309821,6.115974,5.999436
1,SW1116_LARGE_INTESTINE,ACH-000489,5.577413,5.727045,5.111468,6.073250,5.802494,5.824473,5.888821,5.768379,...,6.248653,6.633575,6.378052,6.341043,6.360945,6.333540,6.137271,7.065858,6.832174,6.363064
2,NCIH1694_LUNG,ACH-000431,5.886398,5.574881,5.541259,5.848375,5.665026,5.875548,5.894904,5.839640,...,5.942887,5.946988,5.837980,5.913350,6.137530,5.807546,5.704149,5.881193,5.785208,5.504225
3,P3HR1_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE,ACH-000707,5.770030,6.099229,6.233259,5.543495,5.767759,6.155905,6.111148,5.949481,...,6.516922,6.113791,6.282113,6.248667,6.109480,6.043570,5.846802,6.429402,5.779815,6.241530
4,HUT78_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE,ACH-000509,5.480683,5.469742,6.509397,6.251005,5.190578,5.897085,6.148333,5.607481,...,6.161981,6.777932,6.676390,6.695659,6.751029,6.385056,6.682612,6.757899,6.728570,6.879260
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
923,SF268_CENTRAL_NERVOUS_SYSTEM,ACH-000655,5.977636,6.026483,6.480536,6.112056,5.878324,5.732508,5.981183,6.459139,...,5.547818,5.703861,5.581725,5.506887,5.362247,5.322091,5.556126,5.544802,4.897559,5.506999
924,SF539_CENTRAL_NERVOUS_SYSTEM,ACH-000273,5.957233,6.090834,5.323475,6.145795,5.741201,5.605435,6.184192,6.004195,...,5.713210,5.651439,5.720680,5.387960,5.275798,5.289684,5.494241,5.533795,5.139488,5.452544
925,SNB75_CENTRAL_NERVOUS_SYSTEM,ACH-000504,5.967707,5.931487,5.620542,5.955261,5.935244,5.384674,5.955886,6.239657,...,5.605403,5.317500,5.630315,5.433324,5.330957,5.481404,5.570553,5.146598,5.010639,5.114385
926,HOP92_LUNG,ACH-000825,5.962415,5.992640,6.296222,5.916386,6.043984,5.883976,5.954731,6.181054,...,5.949798,6.249271,6.248746,6.130000,5.873297,5.826041,5.997694,6.411166,6.105394,6.387275
927,MUTZ3_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE,ACH-000084,6.332344,5.812531,5.446330,6.469052,5.501232,6.469954,6.136017,5.479015,...,6.588558,6.548211,6.667652,6.868391,6.598519,5.956474,6.022471,6.862916,7.045115,6.841075

In [8]:
common_cell_lines = set(metabolites.DepMap_ID).intersection(set(rna.index))
common_cell_lines = list(common_cell_lines)
len(common_cell_lines)

913

In [9]:
rna = rna.loc[common_cell_lines]
rna

,TFE3,MMADHC,PABPC1L,RELL2,GPT,GUSB,H4-16,DDB2,RPS4X,HINFP,...,OR2A42,HOXB7,NSA2,UGT2B11,ZNF747,NAA60,MYH4,MTAP,C14orf93,NR3C2
ACH-000358,3.913287,6.007984,3.213653,1.420846,1.625081,6.696166,2.369987,5.709590,10.262246,5.060891,...,-0.013226,4.748231,7.384261,-0.007723,2.879768,5.556855,-0.001724,5.312199,4.041512,1.639166
ACH-000423,4.273677,6.879193,4.231801,3.690205,0.073437,6.552783,1.212081,8.061195,9.607642,3.560331,...,-0.001848,5.633514,6.472930,-0.007723,2.239309,5.003959,0.022428,4.437186,2.588759,0.216482
ACH-000305,4.024231,7.178498,6.549796,3.593886,0.499719,4.346704,2.456533,4.887946,10.061419,3.248688,...,0.053402,5.626614,6.525232,-0.007723,2.137299,4.831581,-0.001724,4.125357,3.675268,0.057915
ACH-000115,3.501985,6.729847,4.876412,5.047585,0.411982,5.889181,3.398910,2.700139,10.894040,3.957948,...,0.009417,0.677703,7.032279,0.830438,2.228630,5.502801,-0.001724,3.839334,2.396547,1.007473
ACH-000405,4.261155,6.403475,5.047037,4.192651,0.742069,5.504427,1.609178,4.615429,10.644783,3.841474,...,0.126525,1.525864,7.585679,0.006466,2.776547,4.913972,-0.001724,3.419875,3.121565,0.043885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ACH-000811,5.096507,6.962989,3.427243,0.838817,0.434514,5.157236,1.175704,4.212187,10.434284,3.669686,...,0.126525,6.491480,7.023314,0.806472,2.383273,5.269029,-0.001724,4.139043,3.015612,0.627949
ACH-000772,4.904892,6.652213,2.978000,2.274537,1.507352,6.120417,1.232438,6.305684,11.145802,4.441381,...,-0.013226,0.282187,6.912601,-0.007723,2.598767,5.291604,-0.001724,3.879158,1.656879,0.029718
ACH-000430,4.907631,6.930202,4.132644,1.800063,0.122459,6.299095,0.678511,4.538440,10.856039,3.372592,...,0.009417,4.387517,7.437790,-0.007723,1.705630,4.052474,-0.001724,5.055180,3.022684,0.728133
ACH-000957,3.535042,6.719364,3.723296,2.379873,1.479221,5.741245,1.217199,5.233025,10.435123,4.063564,...,-0.001848,4.131094,7.469328,0.034427,1.810444,4.785368,1.704206,4.691053,2.988787,2.152383
ACH-000020,3.953176,5.775586,6.012143,3.198194,1.006289,6.328404,2.100765,5.982066,12.285812,4.421818,...,0.286778,0.786108,7.127942,-0.007723,3.295832,4.602184,-0.001724,1.292930,3.621152,0.359425

In [10]:
met_genes = pd.read_csv('drive/My Drive/Colab Notebooks/GP_lab_data/FBA_metabolic_atlas_models/human_gem_associated_genes.csv')
met_genes

              gene_id   Symbol
0     ENSG00000198712   MT-CO2
1     ENSG00000198804   MT-CO1
2     ENSG00000198938   MT-CO3
3     ENSG00000198899  MT-ATP6
4     ENSG00000198886   MT-ND4
...               ...      ...
2879  ENSG00000167751     KLK2
2880  ENSG00000129873    CDY2B
2881  ENSG00000182415    CDY2A
2882  ENSG00000172352    CDY1B
2883  ENSG00000172288     CDY1

[2884 rows x 2 columns]

In [11]:
rna_met = rna[rna.columns[rna.columns.isin(met_genes['Symbol'])]]
rna_met

,GPT,GUSB,NDUFA7,MAN2B2,CYB5R4,NT5M,CERS2,TENT2,GLYATL2,SLC5A2,...,FABP5,CYP4A22,THEM5,PDE6G,ACER1,ENOPH1,ATP2B4,UGT2B11,NAA60,MTAP
ACH-000358,1.625081,6.696166,7.161072,1.782253,5.110691,3.412770,6.241274,4.595374,1.607993,0.158358,...,9.858383,-0.005746,-0.009275,1.068180,0.000394,6.210562,4.740603,-0.007723,5.556855,5.312199
ACH-000423,0.073437,6.552783,6.348634,0.926233,3.074971,2.313297,6.781158,4.316389,0.683654,0.420848,...,7.747192,0.009853,-0.033136,0.983597,0.000394,5.430171,4.146615,-0.007723,5.003959,4.437186
ACH-000305,0.499719,4.346704,4.842416,2.827733,3.520762,2.488910,7.007866,4.093062,0.019389,0.222997,...,7.072976,0.040593,0.124745,1.270915,0.000394,3.857106,3.499179,-0.007723,4.831581,4.125357
ACH-000115,0.411982,5.889181,6.002387,2.269233,1.945067,2.137013,7.076125,3.648721,1.794568,-0.048879,...,6.958943,0.009853,0.002481,0.067278,0.024525,6.512522,1.802112,0.830438,5.502801,3.839334
ACH-000405,0.742069,5.504427,7.110944,3.054234,4.288493,1.640858,5.579747,5.599207,0.046655,-0.048879,...,8.240958,-0.005746,-0.033136,3.655740,0.000394,5.689351,1.490951,0.006466,4.913972,3.419875
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ACH-000811,0.434514,5.157236,6.213981,3.464166,4.427626,1.306580,8.081318,4.883930,0.125358,0.167814,...,7.642639,-0.005746,-0.033136,0.257307,0.000394,5.492344,5.183442,0.806472,5.269029,4.139043
ACH-000772,1.507352,6.120417,6.577882,2.782841,2.370805,2.090823,6.818736,4.955908,4.048804,0.195731,...,9.484702,-0.005746,-0.033136,-0.006798,0.082842,5.755398,4.129259,-0.007723,5.291604,3.879158
ACH-000430,0.122459,6.299095,5.123218,3.072351,2.596416,1.437062,7.264023,4.525830,0.019389,0.465484,...,8.355572,0.009853,-0.033136,0.218541,0.000394,5.292577,6.694022,-0.007723,4.052474,5.055180
ACH-000957,1.479221,5.741245,7.315123,3.562145,3.056095,0.939990,6.675417,4.234586,0.019389,0.805090,...,8.838993,-0.005746,0.092611,0.205396,0.000394,5.790387,3.374747,0.034427,4.785368,4.691053
ACH-000020,1.006289,6.328404,6.425980,3.141171,3.461808,2.935667,6.663525,5.695201,1.142087,0.435917,...,8.833848,-0.005746,0.002481,2.780376,0.059849,5.692870,5.446822,-0.007723,4.602184,1.292930

In [12]:
rna_met.to_csv('drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/CCLE_transcriptomics_tpm_metabolism_related_genes.csv', index = True)

In [13]:
metabolites = metabolites[metabolites['DepMap_ID'].isin(common_cell_lines)]
metabolites

,CCLE_ID,DepMap_ID,2-aminoadipate,3-phosphoglycerate,alpha-glycerophosphate,4-pyridoxate,aconitate,adenine,adipate,alpha-ketoglutarate,...,C56:8 TAG,C56:7 TAG,C56:6 TAG,C56:5 TAG,C56:4 TAG,C56:3 TAG,C56:2 TAG,C58:8 TAG,C58:7 TAG,C58:6 TAG
0,DMS53_LUNG,ACH-000698,6.112727,6.034198,5.896896,6.000532,5.513618,5.868529,5.977177,5.693074,...,6.070239,6.133433,6.091089,6.257711,6.372732,6.202511,5.939576,6.309821,6.115974,5.999436
1,SW1116_LARGE_INTESTINE,ACH-000489,5.577413,5.727045,5.111468,6.073250,5.802494,5.824473,5.888821,5.768379,...,6.248653,6.633575,6.378052,6.341043,6.360945,6.333540,6.137271,7.065858,6.832174,6.363064
2,NCIH1694_LUNG,ACH-000431,5.886398,5.574881,5.541259,5.848375,5.665026,5.875548,5.894904,5.839640,...,5.942887,5.946988,5.837980,5.913350,6.137530,5.807546,5.704149,5.881193,5.785208,5.504225
3,P3HR1_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE,ACH-000707,5.770030,6.099229,6.233259,5.543495,5.767759,6.155905,6.111148,5.949481,...,6.516922,6.113791,6.282113,6.248667,6.109480,6.043570,5.846802,6.429402,5.779815,6.241530
4,HUT78_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE,ACH-000509,5.480683,5.469742,6.509397,6.251005,5.190578,5.897085,6.148333,5.607481,...,6.161981,6.777932,6.676390,6.695659,6.751029,6.385056,6.682612,6.757899,6.728570,6.879260
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
923,SF268_CENTRAL_NERVOUS_SYSTEM,ACH-000655,5.977636,6.026483,6.480536,6.112056,5.878324,5.732508,5.981183,6.459139,...,5.547818,5.703861,5.581725,5.506887,5.362247,5.322091,5.556126,5.544802,4.897559,5.506999
924,SF539_CENTRAL_NERVOUS_SYSTEM,ACH-000273,5.957233,6.090834,5.323475,6.145795,5.741201,5.605435,6.184192,6.004195,...,5.713210,5.651439,5.720680,5.387960,5.275798,5.289684,5.494241,5.533795,5.139488,5.452544
925,SNB75_CENTRAL_NERVOUS_SYSTEM,ACH-000504,5.967707,5.931487,5.620542,5.955261,5.935244,5.384674,5.955886,6.239657,...,5.605403,5.317500,5.630315,5.433324,5.330957,5.481404,5.570553,5.146598,5.010639,5.114385
926,HOP92_LUNG,ACH-000825,5.962415,5.992640,6.296222,5.916386,6.043984,5.883976,5.954731,6.181054,...,5.949798,6.249271,6.248746,6.130000,5.873297,5.826041,5.997694,6.411166,6.105394,6.387275
927,MUTZ3_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE,ACH-000084,6.332344,5.812531,5.446330,6.469052,5.501232,6.469954,6.136017,5.479015,...,6.588558,6.548211,6.667652,6.868391,6.598519,5.956474,6.022471,6.862916,7.045115,6.841075

In [14]:
metabolites = metabolites.set_index('DepMap_ID')
metabolites = metabolites.drop(columns = ['CCLE_ID'])
metabolites.index.name = None
metabolites

,2-aminoadipate,3-phosphoglycerate,alpha-glycerophosphate,4-pyridoxate,aconitate,adenine,adipate,alpha-ketoglutarate,AMP,citrate,...,C56:8 TAG,C56:7 TAG,C56:6 TAG,C56:5 TAG,C56:4 TAG,C56:3 TAG,C56:2 TAG,C58:8 TAG,C58:7 TAG,C58:6 TAG
ACH-000698,6.112727,6.034198,5.896896,6.000532,5.513618,5.868529,5.977177,5.693074,5.923737,5.641242,...,6.070239,6.133433,6.091089,6.257711,6.372732,6.202511,5.939576,6.309821,6.115974,5.999436
ACH-000489,5.577413,5.727045,5.111468,6.073250,5.802494,5.824473,5.888821,5.768379,5.760784,5.914742,...,6.248653,6.633575,6.378052,6.341043,6.360945,6.333540,6.137271,7.065858,6.832174,6.363064
ACH-000431,5.886398,5.574881,5.541259,5.848375,5.665026,5.875548,5.894904,5.839640,5.742613,5.570208,...,5.942887,5.946988,5.837980,5.913350,6.137530,5.807546,5.704149,5.881193,5.785208,5.504225
ACH-000707,5.770030,6.099229,6.233259,5.543495,5.767759,6.155905,6.111148,5.949481,6.342703,6.054781,...,6.516922,6.113791,6.282113,6.248667,6.109480,6.043570,5.846802,6.429402,5.779815,6.241530
ACH-000509,5.480683,5.469742,6.509397,6.251005,5.190578,5.897085,6.148333,5.607481,5.871600,5.128463,...,6.161981,6.777932,6.676390,6.695659,6.751029,6.385056,6.682612,6.757899,6.728570,6.879260
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ACH-000655,5.977636,6.026483,6.480536,6.112056,5.878324,5.732508,5.981183,6.459139,5.642855,6.039198,...,5.547818,5.703861,5.581725,5.506887,5.362247,5.322091,5.556126,5.544802,4.897559,5.506999
ACH-000273,5.957233,6.090834,5.323475,6.145795,5.741201,5.605435,6.184192,6.004195,5.663866,5.758910,...,5.713210,5.651439,5.720680,5.387960,5.275798,5.289684,5.494241,5.533795,5.139488,5.452544
ACH-000504,5.967707,5.931487,5.620542,5.955261,5.935244,5.384674,5.955886,6.239657,5.527619,5.973401,...,5.605403,5.317500,5.630315,5.433324,5.330957,5.481404,5.570553,5.146598,5.010639,5.114385
ACH-000825,5.962415,5.992640,6.296222,5.916386,6.043984,5.883976,5.954731,6.181054,5.820966,6.045409,...,5.949798,6.249271,6.248746,6.130000,5.873297,5.826041,5.997694,6.411166,6.105394,6.387275
ACH-000084,6.332344,5.812531,5.446330,6.469052,5.501232,6.469954,6.136017,5.479015,5.694210,5.078509,...,6.588558,6.548211,6.667652,6.868391,6.598519,5.956474,6.022471,6.862916,7.045115,6.841075

In [15]:
metabolites.to_csv('drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/CCLE_metabolites.csv', index = True)